### ISSUE TITLE
.Subscribe function never gets invoked 

### ISSUE THREAD

**Issue by AngularTx** [2muchcoffeecom/ngx-restangular#1]
Hi,
When using  version 0.0.35 , the Url hits the server and the details can be seen in the network tab. But the .subscribe function doesnot get invoked later ? 

ngOnInit()
 {
     console.log('trying to fetch data....');
    this.restangular.all('users').getList()
    .subscribe((data: any) => {
         console.log('data is fetched....');
         console.log(data[0].id);
    })
   
    
 }
--

**Comment by 2muchcoffeecom** [comment]
Hi, Jaahmed!

You should update to 0.1.7 first. I think thats because you are using version without Observables. Please ping me if you still has this issue after update.

**Comment by 2muchcoffeecom** [comment]
Don't forget to star the  repo if you like it 😉

**Comment by AngularTx** [comment]
Hi
Don't we have the concept of  map in rest? In the examples shown we don't
see any such examples.?

Map and subscribe? Any examples?

Thanks in advance..

**Comment by logvinoleg89** [comment]
Hi, Jaahmed!

Now we work on examples, soon you can see them in Plunker. 
Here some basic example for you:

``` javascript
Restangular.one('accounts', 1234).get()
.map(response =>{
  response.newVariable = 'test';
  return response;
})
.subscribe(response =>{
  console.log(response);
})
```

**Comment by AngularTx** [comment]
Hi ,

Thanks for the reply.

Is version 0.1.4 stable ? Will observables be present in it?

I am working for a bank ,I need to see if they have version 0.1.7. But they
have version 0.1.4 for now.

**Comment by logvinoleg89** [comment]
Yes observables are present in v0.1.4

**Comment by AngularTx** [comment]
Hi, just installed version 0.1.7. It's kind of bit shocking..when I type in
restangular.setBaseUrl... The function is not found. But in the
rectangular.js file I can see the definitions method. Is there an issue or
I need to make changes?

Definition not found in d.ts file. But when I use your git hub repo I see
no issues with it.

Please let me know what could the issue be.

I need to complete a task on this. Would be great if you could reply ASAP.

**Comment by logvinoleg89** [comment]
Please check this [link](https://github.com/2muchcoffeecom/ng2-restangular#how-to-configure-them-globally)

**Comment by AngularTx** [comment]
Is it possible if some one can talk via WhatsApp. I can explain the issue.
I don't find many resource around who are working in this...

**Comment by AngularTx** [comment]
Hi, I have checked your link,also was able to make changes in the git repo
which you have. But if you just download your package and then with some
sample application, we can see that some basic function like setBaseUrl
will not be found.

Is there a specific version of node and npm to be used?

**Comment by rshchpkn** [comment]
Hi, please check this [withConfig](https://github.com/2muchcoffeecom/ng2-restangular#withconfig) link, I think it will help you. Configurating Restangular possible in three ways globaly in [module](https://github.com/2muchcoffeecom/ng2-restangular#how-to-configure-them-globally), in [service](https://github.com/2muchcoffeecom/ng2-restangular#how-to-create-a-restangular-service-with-a-different-configuration-from-the-global-one), or in [component](https://github.com/2muchcoffeecom/ng2-restangular#withconfig)
