### ISSUE TITLE
Circular dependancy when using Restangular in an interceptor

### ISSUE THREAD

**Issue by MartynWynne** [2muchcoffeecom/ngx-restangular#104]
We have a large AngularJS app we are running as an Hybrid while we slowly upgrade it. It currently uses Restangular and we are trying now to switch to ngx-restangular.

In the old app we did a fair bit in the response and request interceptors including generating some new restangular objects based on the response.

When I try to mimic this in the Angular world with ngx-interceptors I am running into what I can only assume is a circular dependency?

old code
```
angular
    .module('cwWebApp.core.init.restangular.hateoas', [
      'restangular'
    ])
    .run(function(RestangularHateoasService) {
      Restangular.addResponseInterceptor(RestangularHateoasService.extractResponse);
      Restangular.addRequestInterceptor(RestangularHateoasService.extractRequest);

```

```
angular
    .module('cwWebApp.core.service.restangularHateoas', [
      'restangular'
    ])
    .service('RestangularHateoasService', RestangularHateoasService);

  function RestangularHateoasService(Restangular) {
    var service = this;
    service.extractResponse = extractResponse;
    return service;

    function extractResponse(element, operation, what, url) {
....
        element[key] = Restangular[isCollection || isAction ? 'allUrl' : 'oneUrl'](targetCollection, value.href);
...
    }
...
```

New code

```
export function RestangularConfigFactory (RestangularProvider: any, restangularHateoasService: RestangularHateoasService): any {
  RestangularProvider.addResponseInterceptor(restangularHateoasService.extractResponse);
  RestangularProvider.addRequestInterceptor(restangularHateoasService.extractRequest);
}

@NgModule({
  imports: [
    SharedModule,
    UpgradeModule,
    RestangularModule.forRoot([RestangularHateoasService], RestangularConfigFactory),
```
So I can see why there is a circular dependency, I just can't see a way around it?

The error is

> core.es5.js:1020 ERROR RangeError: Maximum call stack size exceeded
>     at RegExp.[Symbol.match] (<anonymous>)
>     at String.match (native)
>     at getWrapDetails (http://localhost:3000/vendor.js?d1a95d45:170434:22)
>     at setWrapToString (http://localhost:3000/vendor.js?d1a95d45:171973:75)
>     at createWrap (http://localhost:3000/vendor.js?d1a95d45:169567:10)
>     at Object.<anonymous> (http://localhost:3000/vendor.js?d1a95d45:172509:10)
>     at apply (http://localhost:3000/vendor.js?d1a95d45:166278:25)
>     at Object.bind (http://localhost:3000/vendor.js?d1a95d45:171702:12)
>     at createServiceForConfiguration (http://localhost:3000/vendor.js?d1a95d45:218101:45)
>     at providerConfig.$get (http://localhost:3000/vendor.js?d1a95d45:218114:16)

Thanks in advance

**Comment by rshchpkn** [comment]
Hello @MartynWynne, unfortunately you shouldn't have used restangular in restangular config. You can try the following but it's not what can be considered a solution:

You can create service where you could make new instance of restangular as class property;
```
// Service
@Injectable()
export class RestService  {
  public restangular;
  
  constructor(
    private http: RestangularHttp,
    private injector: Injector
  ) {
    this.restangular = new Restangular(
      {}, //config object
      injector,
      http
    ).withConfig(provider => {
      //here you can config restangular
    });
  }
}
```
AppModule
```
imports: [
    RestangularModule.forRoot([API_URLS, Store, RestangularService], RestangularFunction),
//...
]
```
