### ISSUE TITLE
Property 'extendModel' does not exist on type 'Restangular'

### ISSUE THREAD

**Issue by ulanmurzatayev** [2muchcoffeecom/ngx-restangular#105]
When trying to extend the Restangular model using `extendModel` method I get the following error:
`Property 'extendModel' does not exist on type 'Restangular'`

**Comment by rshchpkn** [comment]
Hi @murzatayev, properties extendModel, extendCollection, addElementTransformer are available in configuration function. More details in this article [Configuring Restangular](https://github.com/2muchcoffeecom/ngx-restangular#configuring-restangular) 
Example:
```
// Function for settting the default restangular configuration
export function RestangularConfigFactory (RestangularProvider) {
  RestangularProvider.setBaseUrl('http://www.google.com');
}

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
  ],
  imports: [
    // Global configuration
    RestangularModule.forRoot(RestangularConfigFactory),
  ]
})
export class AppModule {}
```

**Comment by ulanmurzatayev** [comment]
@rshchpkn, right, but it also should be available on the Restangular object according to this example
https://github.com/2muchcoffeecom/ngx-restangular#adding-custom-methods-to-models

Thus giving the developers opportunity to extend the model at runtime, rather than in config.
The issue is that this example does not even run.

**Comment by rshchpkn** [comment]
@murzatayev thanks for the response. We have reconsidered the possibility of extending restangular at runtime.
This is fixed and will be available in next release of restangular.
