### ISSUE TITLE
PUT result is not transformed by the element transformer

### ISSUE THREAD

**Issue by ulanmurzatayev** [2muchcoffeecom/ngx-restangular#107]
Element transformers are not executed when a server return a result of PUT.

**Comment by rshchpkn** [comment]
Hi @murzatayev. Can you please provide more details about the issue? As I couldn't reproduce it.

**Comment by ulanmurzatayev** [comment]
Hi @rshchpkn. 

In my case I transform every element returned by the server to instances of some class, let's name it `A`

```
RestangularProvider.addElementTransformer('a', false, a => new A(a));
```

then somewhere else I call put method like so:
```
...
update(a) {
    a.put().subscribe(result => { 
        // This does not work because the result was not transformed
        // result.methodOfA();
        // so have to manually transform the result to an instance of A
       new A(result).methodOfA();
    });
}
...
```

From the snippet above you can see that the transformer was never executed for the PUT method. Whereas it works just fine for the results returned by GET.

**Comment by rshchpkn** [comment]
Hi @murzatayev, I couldn't reproduce this issue. On the attached image I have updated model returned from PUT request  with "test" field.
<img width="203" alt="screen shot 2017-10-11 at 11 10 25" src="https://user-images.githubusercontent.com/22593160/31428919-28f0dafe-ae75-11e7-9ee4-a049ba5e3367.png">
