### ISSUE TITLE
Response contain wrapper pollution

### ISSUE THREAD

**Issue by TheSegfault** [2muchcoffeecom/ngx-restangular#108]
Hi, self explainatory screenshot.
I'm supposed to get an array of 3 objects, I get the 3 objects + 300000 functions wrapper.

![3](https://user-images.githubusercontent.com/5268918/31615000-71273842-b288-11e7-8a90-42bf08cb78b7.PNG)
![2](https://user-images.githubusercontent.com/5268918/31615002-72d4303c-b288-11e7-893d-79a01d1a2c8d.PNG)

Here is my code 

```
 private loadProjects() {
    this.userService.getProjects(this.user.id).subscribe(
      projects => {
        console.log('full response', projects);
        this.projectList = projects;
      }, err => {
        console.error(err);
      }
    );
  }
```
```
getProjects(userId: number): Observable<any> {
    return this.restangular.one('utilisateurs', userId).all('ownedProjects').getList();
  }
```

**Comment by rshchpkn** [comment]
Hello @TheSegfault, If you want to use Restangular without its helper methods, please set this config option in true value  [setPlainByDefault](https://github.com/2muchcoffeecom/ngx-restangular#setplainbydefault)
