### ISSUE TITLE
ngx-restangular v1.0.13, rxjs v5.5.0  Incompatible

### ISSUE THREAD

**Issue by WuWeiSen** [2muchcoffeecom/ngx-restangular#110]
![图片描述][1]

## it can work at ngx-restangular v1.0.13, rxjs v5.4.3 

[1]: https://sfault-image.b0.upaiyun.com/373/221/3732215587-59e9badc361d6

**Comment by kotmatpockuh** [comment]
+1

**Comment by jaizquierdogalan** [comment]
+1

**Comment by TheSegfault** [comment]
I had the exact same issue
Refering to https://github.com/2muchcoffeecom/ngx-restangular/issues/109

**Comment by tesseris** [comment]
+1

**Comment by logvinoleg89** [comment]
Please update to 1.1.0 version!

**Comment by AndreyNikolayev** [comment]
still remains on 1.1.0 with rxjs v5.5.2

**Comment by logvinoleg89** [comment]
@AndreyNikolayev thanks for letting us know. We've fixed that.
