### ISSUE TITLE
If response body is empty, subscription won't get into 'onSuccess' block

### ISSUE THREAD

**Issue by kotmatpockuh** [2muchcoffeecom/ngx-restangular#112]
If server returns empty body response: such code won't work (i can't handle success subscription):

```
    this.apiSubscription.add(this.profileService.someAPi(data)
      .subscribe(
        (response) => {
          console.log('its ok', response);
        },
        (error) => {
          console.log('its error', error);
        }));
```

(v1.0.13)

but i tested the same in v1.0.11 and everything was fine

**Comment by awinnen** [comment]
issue also exists on v1.1

**Comment by awinnen** [comment]
this happens since  ec90952

if we add the default interceptor again, it will work with empty response.
