### ISSUE TITLE
Installing in Angular 4 project

### ISSUE THREAD

**Issue by byhoratiss** [2muchcoffeecom/ngx-restangular#114]
I'm having problems building a project with Angular4.
When installing with ```npm install --save ngx-restangular``` it has dependencies in angular5:
```
npm WARN ngx-restangular@1.1.1 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-restangular@1.1.1 requires a peer of @angular/platform-browser@^5.0.0 but none is installed. You must install peer dependencies yourself.
```
But I cannot use angular5 because of other dependencies, any idea how to solve this?
Thank you for this great tool!

**Comment by byhoratiss** [comment]
I've realized that installing a previous version works fine, but, it don't want to stay too much behind of master release. This is not an issue, of course, but I would like to read an answer!

I installed the 1.0.13 release. To help others with this issue:
```
npm install --save ngx-restangular@1.0.13
```

**Comment by logvinoleg89** [comment]
Hi @byhoratiss, thanks for quick reaction :) We've changed respective documentation [chapter](https://github.com/2muchcoffeecom/ngx-restangular#how-do-i-add-this-to-my-project-in-angular-4)
