### ISSUE TITLE
NullInjectorError: No provider for Restangular!

### ISSUE THREAD

**Issue by vinishanto** [2muchcoffeecom/ngx-restangular#117]
Hi I am getting this error while using ngx-restangular.

ERROR 
Error
__zone_symbol__currentTask: Object { runCount: 0, _state: "notScheduled", type: "microTask", … }
columnNumber: 19
fileName: "http://localhost:4200/vendor.bundle.js line 3337 > eval"
lineNumber: 1119
message: "StaticInjectorError[Restangular]: \n  StaticInjectorError[Restangular]: \n    NullInjectorError: No provider for Restangular!"
ngDebugContext: Object { view: {…}, nodeIndex: 17, nodeDef: {…}, … }
ngErrorLogger: function bound ()
ngTempTokenPath: null
ngTokenPath: Array [ Restangular() ]

StaticInjectorError[Restangular]: 
    NullInjectorError: No provider for Restangular!
Stack trace:
_NullInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1119:19
resolveToken@webpack-internal:///../../../core/esm5/core.js:1407:17
tryResolveToken@webpack-internal:///../../../core/esm5/core.js:1349:16
StaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1220:20
resolveToken@webpack-internal:///../../../core/esm5/core.js:1407:17
tryResolveToken@webpack-internal:///../../../core/esm5/core.js:1349:16
StaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1220:20
resolveNgModuleDep@webpack-internal:///../../../core/esm5/core.js:10781:12
NgModuleRef_.prototype.get@webpack-internal:///../../../core/esm5/core.js:12002:16
resolveDep@webpack-internal:///../../../core/esm5/core.js:12498:12
createClass@webpack-internal:///../../../core/esm5/core.js:12360:29
createDirectiveInstance@webpack-internal:///../../../core/esm5/core.js:12207:37
createViewNodes@webpack-internal:///../../../core/esm5/core.js:13645:53
callViewAction@webpack-internal:///../../../core/esm5/core.js:14077:13
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:13986:13
createViewNodes@webpack-internal:///../../../core/esm5/core.js:13673:5
createRootView@webpack-internal:///../../../core/esm5/core.js:13535:5
callWithDebugContext@webpack-internal:///../../../core/esm5/core.js:14936:39
debugCreateRootView@webpack-internal:///../../../core/esm5/core.js:14237:12
ComponentFactory_.prototype.create@webpack-internal:///../../../core/esm5/core.js:11156:37
ComponentFactoryBoundToModule.prototype.create@webpack-internal:///../../../core/esm5/core.js:4118:16
ApplicationRef.prototype.bootstrap@webpack-internal:///../../../core/esm5/core.js:5929:40
PlatformRef.prototype._moduleDoBootstrap/<@webpack-internal:///../../../core/esm5/core.js:5656:74
PlatformRef.prototype._moduleDoBootstrap@webpack-internal:///../../../core/esm5/core.js:5656:13
PlatformRef.prototype.bootstrapModuleFactory/</</<@webpack-internal:///../../../core/esm5/core.js:5577:21
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:392:17
onInvoke@webpack-internal:///../../../core/esm5/core.js:4825:24
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:391:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:142:24
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:873:52
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:425:17
onInvokeTask@webpack-internal:///../../../core/esm5/core.js:4816:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:602:25

I am using,

angular/cli: "^1.5.3,
ngx-restangular: "^2.0.1",

**Comment by logvinoleg89** [comment]
Hi @vinishanto . Could you please provide response from running `npm ls ngx-restangular` and `npm ls --depth=0` in terminal.

**Comment by ghost** [comment]
hello @logvinoleg89 
i'm also having the same problem on angular 5.1.2

here's my `npm ls ngx-restangular` 
-----------------
-- ngx-restangular@2.0.2


here's my `npm ls --depth=0` 
-----------------
![image](https://user-images.githubusercontent.com/18378120/34510910-ce2380d0-f092-11e7-90bd-124b337d1ef7.png)

thanks for helping
  
  
  
  EDIT:
refreshing the npm_modules folder as well as updating angular to 5.1.3 made it worked. If anyone has a similar problem, here is the list of npm packages I used (for ngx-restangular/angular builds):
        "@ angular/common": "5.1.3",
        "@ angular/compiler": "5.1.3",
        "@ angular/core": "5.1.3",
        "@ angular/forms": "5.1.3",
        "@ angular/http": "5.1.3",
        "@ angular/platform-browser": "5.1.3",
        "@ angular/platform-browser-dynamic": "5.1.3",
        "@ angular/router": "5.1.3",
        "core-js": "2.5.3",
        "lodash": "4.17.4",
        "ngx-restangular": "2.0.2",
        "reflect-metadata": "0.1.10",
        "rxjs": "5.5.6",
        "typescript": "2.6.2",
        "zone.js": "0.8.19"

**Comment by rshchpkn** [comment]
Hello @vinishanto . If you still can reproduce this, then check the @stonedleaf answer. If with this versions there is still the same error please reopen the issue.

**Comment by ghost** [comment]
Hello @rshchpkn
After some checking, since the error occurred again for me after changing angular versions,
It seems like the problem is with the npm package. It is including the node_modules folder of the restangular source.. i think its packages are conflicting with the other packages of the user's project

Deleting the node_modules folder of ngx-restangular did the trick. Changing versions of other packages in the project no longer trigger the said error
I guess you should remove the said folder

Please try check it again and see if it fixes the problem

**Comment by mspivak** [comment]
@stonedleaf suggestion didn't do the trick for me. I'm still getting:
`NullInjectorError: No provider for Restangular!`
