### ISSUE TITLE
NullInjectorError: No provider for Injector!

### ISSUE THREAD

**Issue by Xepe** [2muchcoffeecom/ngx-restangular#119]
Hello, 

I got the following issue using angular 5.1.0 beta 2 and ngx-restangular 2.0.1, I am testing it with a beta version because probably I will need to upgrade my project to Angular 5.1.0 because I need the "export JitCompilerFactory" (this feature was released in Angular 5.1.0 beta 2 :) ) 

![image](https://user-images.githubusercontent.com/2806076/33284349-661adbae-d374-11e7-9faa-2244aa9a1b7b.png)

Regards

**Comment by logvinoleg89** [comment]
Hi @Xepe . Could you please provide response from running `npm ls ngx-restangular` and `npm ls --depth=0` in terminal.

**Comment by Xepe** [comment]
You can close it, it is working in the new version 2.0.2 :) 

Thanks!
