### ISSUE TITLE
Subscriber never gets isStopped or closed true.

### ISSUE THREAD

**Issue by Xepe** [2muchcoffeecom/ngx-restangular#12]
Hello, 

I am trying to implemente [angular2-busy](https://github.com/devyumao/angular2-busy), but I found that the Subscriber using customPOST never got closed or isStopped. 

![image](https://cloud.githubusercontent.com/assets/2806076/21462280/c081079a-c91f-11e6-9ecc-baa050981bc3.png)

In the image for the first subscriber I am using customPOST, and the second one is from http post (angular 2 http). 

not sure what is going on. 

Regards.

**Comment by logvinoleg89** [comment]
Its normal behavior because restangular  using BehaviorSubject (Hot Observable). 
If making http request we get Cold Observable.
To solve your problem you can use take() or any similar operator
Example: 
````
let observable =  this.restangular.all('...').customPOST(...);
let sub = observable.take(1).subscribe(res => {
  console.log(res);
}, err => {
  console.log(err);
});
    
console.log(sub);
````
