### ISSUE TITLE
Circular reference : Router inside RestangularConfigFactory

### ISSUE THREAD

**Issue by davidbonachera** [2muchcoffeecom/ngx-restangular#120]
When we inject the Router inside the module root.
`RestangularModule.forRoot([Router],RestangularConfigFactory),`

We have this error : 
`Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded`

I used the router to do redirection on the request interceptors.

I didn't had this error with angular 4.

Here are my dependencies (angular5, ngx-restangular 2):  
```javascript
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@swimlane/ngx-datatable": "^11.1.4",
    "angular-web-storage": "^1.0.1",
    "chart.js": "2.6.0",
    "console-emoji": "0.0.2",
    "core-js": "2.5.0",
    "lodash": "4.17.4",
    "moment": "2.18.1",
    "ng2-charts": "1.6.0",
    "ngx-bootstrap": "^1.9.3",
    "ngx-restangular": "^2.0.1",
    "ngx-toastr": "^6.5.0",
    "rxjs": "^5.5.2",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.17"
  },
```

**Comment by logvinoleg89** [comment]
@davidbonachera I've setup test project with your dependencies and there was no such error. Can you give me more details to solve this issue?

**Comment by rshchpkn** [comment]
@davidbonachera. If you still can reproduce error please reopen this issue.
