### ISSUE TITLE
Cannot setup Config Factory properly

### ISSUE THREAD

**Issue by bartando** [2muchcoffeecom/ngx-restangular#122]
Hi, I'm unable to setup the RestangularConfigFactory properly. There is no proper documentation. Everyone shows only half of the files or so. 

My app module:

`imports: [
      RestangularModule.forRoot([AuthService], RestangularConfigFactory)
],
providers: [
     TokenStorage,
     AuthService
]`

the restConfig file

`
export function RestangularConfigFactory (RestangularProvider, authService: AuthService) {
    RestangularProvider.setBaseUrl(environment.apiUrl);

    // This function must return observable
    var refreshAccesstoken = function () {
        // Here you can make action before repeated request
        return authService.refreshToken();
    };

    RestangularProvider.addErrorInterceptor((response, subject, responseHandler) => {
        if (response.status === 403) {

            refreshAccesstoken()
                .map(refreshAccesstokenResponse => {
                    console.log("Error Interceptor:", response.request);
                    return response.repeatRequest(response.request);
                })
                .subscribe(
                    res => responseHandler(res),
                    err => subject.error(err)
                );

            return false; // error handled
        }
        return true; // error not handled
    });
}
`

and I'm getting ERROR RangeError: Maximum call stack size exceeded

I would just like to catch the Unauthorized error, to refresh my JWT token and call the calls again so they get trough.

**Comment by rshchpkn** [comment]
Hi @bartando. Do you use Restangular in AuthService? Unfortunately it's not possible use Restangular in service you import in Config Factory. My suggestion would be using native Http or HttpClient to make refresh token requests. If with my suggestions you still can reproduce error please reopen the issue.
