### ISSUE TITLE
Support TypeScript 2.5.x in Angular v5.1.x

### ISSUE THREAD

**Issue by Splaktar** [2muchcoffeecom/ngx-restangular#124]
The Angular CLI sets up projects with TypeScript 2.5.3 now (v1.6.2+, released about 20 days ago) (https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/package.json#L48). 

This library doesn't support TypeScript 2.5 (https://github.com/2muchcoffeecom/ngx-restangular/blob/master/package.json#L122).

You should also look into making TypeScript a peer dependency and dev dependency, and removing it from the `dependencies` list. This is probably true for everything in the current `dependencies` list: https://github.com/2muchcoffeecom/ngx-restangular/blob/master/package.json#L115

**Comment by rshchpkn** [comment]
Will be working on it today :)

**Comment by logvinoleg89** [comment]
Fixed in 2.1.0
