### ISSUE TITLE
How to change authorization header at run-time

### ISSUE THREAD

**Issue by ap1969** [2muchcoffeecom/ngx-restangular#125]
Hi,
First, thanks for creating ngx-restangular. When I updated from Angular 1 to 4, I was relieved to a Restangular version available!

But I have one question: I make an initial request to the server without authentication, but once the user logs in, I have an Authorization header to add. Hwoever, i can't work out how to add (or delete, after they logout) headers outside of the normal service configuration.

Any suggestions?

Regards,
Andy

**Comment by rshchpkn** [comment]
Hi @Notifium, One of the solutions is to provide service with some token variable in RestangularConfig. Then use this service variable in request interceptor to add new header.
