### ISSUE TITLE
Http is deprecated

### ISSUE THREAD

**Issue by piwko28** [2muchcoffeecom/ngx-restangular#126]
Restangular uses depricated dependencies (HttpModule).
HttpClient should be used instead.
Are there any plans to migrate?

**Comment by Netizen29** [comment]
When can we expect the upgrade?
One of our libraries provide a decorator for requests made by HttpClient and it would be very handy.

**Comment by rshchpkn** [comment]
Hi @piwko28, Restangular with HttpClientModule dependency is available in version 2.2.1
