### ISSUE TITLE
Missing types in Restangular typescript definition after Angular 5 upgrade

### ISSUE THREAD

**Issue by KillboyPowerhead90** [2muchcoffeecom/ngx-restangular#128]
After upgrading my project from Angular 4.0.0 to Angular 5.2.2, i've updated several other modules and also ngx-restangular from 1.0.13 to ngx-restangular 2.0.2.
This upgrade leads to a big problem: 
The restangular typescript definitions (*.d.ts) are not typed anymore and always returns "any".
e.g. Restangular.get() is declared like "any" instead of "Observable(Of T)".

Is it a known issue or am i missing something?

**Comment by rshchpkn** [comment]
Hi @KillboyPowerhead90 unfortunately there are no type definition for Restagular methods.
