### ISSUE TITLE
StaticInjectorError(AppModule)[Restangular -> Injector]

### ISSUE THREAD

**Issue by gmalagutti** [2muchcoffeecom/ngx-restangular#130]
The issue appeared to be verified and closed but I still have it (regression?)
The error is:
core.js:1440 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[Restangular -> Injector]: 
  StaticInjectorError(Platform: core)[Restangular -> Injector]: 
    NullInjectorError: No provider for Injector!
Error: StaticInjectorError(AppModule)[Restangular -> Injector]: 
  StaticInjectorError(Platform: core)[Restangular -> Injector]: 
    NullInjectorError: No provider for Injector!
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10837)
    at _createClass (core.js:10878)

This is the warning I got when I installed Restangular
├── UNMET PEER DEPENDENCY @angular/common@5.2.2
├── UNMET PEER DEPENDENCY @angular/core@5.2.2
└─┬ ngx-restangular@2.0.2 
  ├── @types/lodash@4.14.104 
  └── typescript@2.4.2 

And this is the version of Angular CLI installed
Angular CLI: 1.6.5
Node: 6.9.4
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 2.0.0-beta.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

Any hint on the solution? Anybody else experiencing it?

**Comment by rshchpkn** [comment]
Hi @gmalagutti, Unfortunately I couldn’t reproduce your issue. My suggestion is to install the latest version. If the problem still appears, reopen issue with link to repo where it can be reproduced.
