### ISSUE TITLE
Add Custom Header in Http Request using ngx-restangular in Angular 4

### ISSUE THREAD

**Issue by swetansh** [2muchcoffeecom/ngx-restangular#134]
[Issue Link](https://stackoverflow.com/questions/49276627/add-custom-header-in-http-request-using-ngx-restangular-in-angular-4)

**Comment by swetansh** [comment]
I am using ngx-restangular for http requests in Angular 4. I have to set up a custom header at some event taking some input from user and after that the Token is created which is to be passed to the Requestheader in the API.

**Comment by rshchpkn** [comment]
Hi @swetansh, ngx-restangular doesn`t use @angular/http Headers class. If you want to add header you need to use object instead. e.g:
```
this.headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Basic ' + btoa(this.model.username + ':' + this.model.password),
};
```

**Comment by swetansh** [comment]
how to use this.headers object inside get or post request?
@rshchpkn

**Comment by rshchpkn** [comment]
Hi @swetansh, here is an example: 
```
this.restangular.one('users', 3).get({}, {customHeader: 'custom header content'})
```
