### ISSUE TITLE
request repeat with old token

### ISSUE THREAD

**Issue by staskuban** [2muchcoffeecom/ngx-restangular#141]
Hi! I,ve a problem.

I implement JWT in my app but after updating access token  last request uses old access token:
_config.factory.ts_
```
export function restangularConfigFactory(RestangularProvider,  jwt: JwtProvider) {
  RestangularProvider.setBaseUrl(`${APIADDR}${APIVER}/`);
  RestangularProvider.setDefaultHeaders({'Content-Type': undefined});

  var refreshAccesstoken = function () {
    return jwt.tokenRefresh()
  };


  RestangularProvider.addFullRequestInterceptor((element, operation, path, url, headers, params) => {
    let jwt = JSON.parse(localStorage.getItem('app_data')) || null;
    if (jwt && operation === 'post') headers.Authorization = 'JWT ' + jwt.jwt;
    return {
      params: params,
      headers: headers,
      element: element
    }
  });
  RestangularProvider.addResponseInterceptor((data) => {
    return data;
  });

  RestangularProvider.addErrorInterceptor((response, subject, responseHandler) => {
      if (response.status === 419) {
        refreshAccesstoken().switchMap((refreshAccesstokenResponse: any) => {
          response.request.headers.set('Authorization', 'JWT ' + refreshAccesstokenResponse.token);
          let sjwt = JSON.parse(localStorage.getItem('app_data')) || {};
          sjwt.jwt = refreshAccesstokenResponse.token;
          localStorage.setItem('twobsafe', JSON.stringify(sjwt));
          return response.repeatRequest(response.request)
        }).subscribe(
          res => responseHandler(res),
          err => subject.error(err)
        );
        return false
      }
      return true;
    }
  )
}
````

_provider_
````
@Injectable()
export class JwtProvider {

  constructor(private http: HttpClient) {}


  public tokenRefresh() {
    const jwttoken = JSON.parse(localStorage.getItem('app_data')) || null;
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type': 'application/json',
        "Authorization": "JWT " + jwttoken.jwt
      })
    };
    return this.http.post(`${APIADDR}${APIVER}/jwt/v1.0/refresh`, {}, httpOptions)
  }
}
````
In console all looks like: 

1. first request - error with token expired
2. refreshing token (second request) - new token delivired and passed to config factory
3. retrying first request - in header i see old expired token
<img width="753" alt="2018-05-21 17 21 43" src="https://user-images.githubusercontent.com/29224919/40312406-79ed0194-5d1b-11e8-8dd3-1e985e990297.png">

Packages
1.  "ngx-restangular": "^2.0.1";
2.   "angular/core": "5.0.0",
    "angular/http": "5.0.0",

**Comment by Mcmtechnologies** [comment]
I got the same problem. 
I saw old token after set new token:
console.log(response.request.headers.get('Authorization')); => return old token.
sponse.request.headers.set('Authorization', 'JWT ' + refreshAccesstokenResponse.token);
console.log(response.request.headers.get('Authorization')); => return old token again

**Comment by tonyleviet** [comment]
I got the same problem.
I saw old token after set new token:
console.log(response.request.headers.get('Authorization')); => return old token.
sponse.request.headers.set('Authorization', 'JWT ' + refreshAccesstokenResponse.token);
console.log(response.request.headers.get('Authorization')); => return old token again

**Comment by marvin-dent** [comment]
Same problem. Please advise.

EDIT: Found the answer:
HttpRequests are immutable (https://angular.io/guide/http#immutability). Instead of directly setting headers, the old request needs to be cloned and assigned new headers.

```
const newHeaders = new HttpHeaders(AuthService.getRequestHeaders());
let newReq = response.request.clone({headers: newHeaders});
return response.repeatRequest(newReq)
```

I was going off of the example on the main page. Please modify the example if this makes sense.
Thanks!

**Comment by faradoxuz** [comment]
I have same problem

> let newReq = response.request.clone({headers: newHeaders});

this is the perfect, thank you @marvin-dent 
please modify the example
