### ISSUE TITLE
(SystemJS) Unexpected token 

### ISSUE THREAD

**Issue by smanoj005** [2muchcoffeecom/ngx-restangular#142]
**I am getting the below error** 

Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:3:14)
	    at eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:496:4)
	    at eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:497:3)
	Evaluating http://localhost:49695/node_modules/rxjs
	Evaluating http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js
	Evaluating http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.js
	Evaluating http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/index.js
	Evaluating http://localhost:49695/src/app/app.module.js
	Evaluating http://localhost:49695/src/main.js
	Error loading http://localhost:49695/src/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:3:14)
	    at eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:496:4)
	    at eval (http://localhost:49695/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.js:497:3)
	Evaluating http://localhost:49695/node_modules/rxjs

**Systemjs.config.js for the ref**

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': '/node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            // other libraries

            'ng2-restangular': '/node_modules/ng2-restangular/dist/esm/src',
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'lodash': 'npm:lodash'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            rxjs: {
                defaultExtension: 'js'
            },
            lodash: {
                main: './index.js',
                defaultExtension: 'js'
            },
            "ng2-restangular": {
                main: './index',
                defaultExtension: 'js'
            }
        }
    });
})(this);

**Comment by rshchpkn** [comment]
Hi @smanoj005, `ng2-restangular` was changed to the `ngx-restangular`. Please create a new issue if it is relevant with a new version
