### ISSUE TITLE
"ngx-restangular" error in angular 5

### ISSUE THREAD

**Issue by smanoj005** [2muchcoffeecom/ngx-restangular#143]
In our application we have used the "ngx-restangular": "^1.0.13" for  "@angular/": "~4.3.4" & "rxjs": "5.0.1". In this restangular is perfectly working for me.

I have upgrade the angular  to  "~5.2" and  "rxjs" to  "^5.5.2".  Maintained the  same "ngx-restangular": "^1.0.13".  I am getting the  below error

![image](https://user-images.githubusercontent.com/39886103/41035252-b4fc69ba-69a9-11e8-9c72-1fb54d9824c8.png)

 systemjs.config as below

![image](https://user-images.githubusercontent.com/39886103/41035277-c9393f98-69a9-11e8-8f9c-d4cfb8eb8ff8.png)

![image](https://user-images.githubusercontent.com/39886103/41035296-d8906368-69a9-11e8-8074-5ce72ee042eb.png)

Please help me to use ngx-restangular for angular 5. 

Thanks in advance.

**Comment by rshchpkn** [comment]
Hi @smanoj005, Is this issue still present with restangular v4?

**Comment by rshchpkn** [comment]
If the issue is still present with the latest angular and restangular version, notify me and I will reopen the issue
