### ISSUE TITLE
ngx-restangular not triggering ngx-loadingbar loading bar

### ISSUE THREAD

**Issue by dericatienza** [2muchcoffeecom/ngx-restangular#144]
I'm trying to get ngx-restangular to work with ngx-loadingbar. Bare requests made through HttpClient and route changes trigger the loading bar but requests made through Restangular just won't seem to trigger the loading bar. customPUTs and customPOSTs also trigger the loading bar.

**Comment by logan-jobzmall** [comment]
@dericatienza You need to add it to the RestangularConfigFactory method:

```
RestangularProvider.addFullRequestInterceptor(() => loader.start());
  RestangularProvider.addErrorInterceptor(() => loader.complete());
  RestangularProvider.addResponseInterceptor((data: any) => {
    loader.complete();
    return data || {};
  });
```

**Comment by rshchpkn** [comment]
@dericatienza Restangular isn't using HttpClient so `ngx-loadingbar` interceptor won't work. You could try @logan-jobzmall solution
