### ISSUE TITLE
Unable to post first record to an object

### ISSUE THREAD

**Issue by ceres1987** [2muchcoffeecom/ngx-restangular#149]
I'm trying out restangular and have a simple json server running. I get the following error when I try to post the first record to an object called 'feedback' in the db.json file:
http://localhost:3000/feedback 404 (Not Found)

If I manually add the first record to the db.json file, then the error goes away and I can add subsequent records without issue. Also, there are other components that perform a restangular getList() and get() on other objects that have no problems reading the data. (The data for those objects were pasted into the file just to see if I could do a simple read.)

Below is the service for the feedback object. That code works only when there at least one record for that object in the db.json file. And below that are the software versions I'm using. Any assistance on what I'm doing wrong is greatly appreciated.

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Restangular } from 'ngx-restangular';

//this is the Feedback class that contains person's name, phone, etc.
import { Feedback } from '../shared/feedback';

@Injectable({
  providedIn: 'root'
})

export class FeedbackService {

  constructor(private restangular: Restangular) { }
  
  submitFeedback(newFeedback: Feedback): Observable<Feedback> {
    console.log("new feedback is: ", newFeedback);
    return this.restangular.all('feedback').post(newFeedback);    
  }
}

==============
Software Versions:
==============
restanguler: 3.0.0
npm: 6.1.0
Node: 10.6.0
Angular CLI: 6.0.8
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Comment by rshchpkn** [comment]
@ceres1987 Please notify me If the issue is still relevant
