### ISSUE TITLE
Duplicate part of angular

### ISSUE THREAD

**Issue by tamascsaba** [2muchcoffeecom/ngx-restangular#15]
When I see ```ng2-restangular/dist/umd/ng2-restangular.js``` it is contains parts of angular framework.
Example:
```
XHRConnection,
CookieXSRFStrategy,
XHRBackend,
RequestOptions,
Request
.....
```

I use browserify, which can not dedupe this parts and caouse many anomaly like https://github.com/angular/angular/issues/9294

**Comment by tamascsaba** [comment]
@tairezzzz @logvinoleg89 @rshchpkn ???

**Comment by tamascsaba** [comment]
I maked a P.R: https://github.com/2muchcoffeecom/ng2-restangular/pull/16, pls review it thx :)

**Comment by logvinoleg89** [comment]
@tamascsaba Thanks for this 8-)

**Comment by tamascsaba** [comment]
Please update the package.json version and release to npm, thx :)
