### ISSUE TITLE
Is it possible to intercept requests for mocking a fake back end?

### ISSUE THREAD

**Issue by chorsnell** [2muchcoffeecom/ngx-restangular#153]
I'm trying to use `addFullRequestInterceptor` to intercept the requests as is mentioned here https://github.com/2muchcoffeecom/ngx-restangular/issues/95 however all it seems to be able to do is just modify the request headers and then send it out anyway.

There doesn't seem to be a way to actually block the real request and replace the body with mock data.

The docs for `addFullRequestInterceptor` seem fairly light - https://github.com/2muchcoffeecom/ngx-restangular#addfullrequestinterceptor

`addResponseInterceptor` is no good also, as its doesn't happen until after the actual response from the server.

Any ideas?

**Comment by jcjmcclean** [comment]
+1

**Comment by rshchpkn** [comment]
Hi!
There is no such ability in Restangular, but you can use [Angular way](https://angular.io/guide/http#testing-http-requests) to fake requests. Angular [HttpBackend](https://angular.io/api/common/http/HttpBackend) is used inside Restangular.
