### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by hijamoya** [2muchcoffeecom/ngx-restangular#154]
Please update to support angular7

**Comment by Roycohen** [comment]
Is it supported?

**Comment by tairezzzz** [comment]
Team is working on it. Will update you here once it's done

**Comment by Roycohen** [comment]
@tairezzzz,

Thanks!!!
Waiting for it.

**Comment by rshchpkn** [comment]
Hi @Roycohen @hijamoya, version 4.0.1 published
Any feedback would be appreciated
