### ISSUE TITLE
HAL+JSON support

### ISSUE THREAD

**Issue by 8rV1n** [2muchcoffeecom/ngx-restangular#155]
Does this framework support HAL+JSON(`applicaion/hal+json`)?

**Comment by rshchpkn** [comment]
Hi @ArvinSiChuan, Do you know any public api that has such endpoint where I could check it?

**Comment by 8rV1n** [comment]
@rshchpkn it's been 9 month long, things went smoothly fast. Googled it and maybe angular4-hal will do this.

**Comment by rshchpkn** [comment]
@ArvinSiChuan got your points, thanks for your reply 👍
