### ISSUE TITLE
Set default headers dynamically 

### ISSUE THREAD

**Issue by akvaliya** [2muchcoffeecom/ngx-restangular#158]
We have a option to set default headers in RestAngular like below for angular 2+

```
export function RestangularConfigFactory (RestangularProvider) {
  RestangularProvider.setBaseUrl('http://api.restngx.local/v1');
  RestangularProvider.setDefaultHeaders({'Authorization': 'Bearer UDXPx-Xko0w4BRKajozCVy20X11MRZs1'});
}
```

What i want to do is set/append new headers after login.

Can anyone tell me how can i achieve this?  I don't want to set interceptor for this.

Thanks in advance!

**Comment by osiastedian** [comment]
You can handle the login on "main.ts" before "platformBrowserDynamic().bootstrapModule(AppModule)" and store the token on the "environment" object.

**Comment by rshchpkn** [comment]
@akvaliya The easiest way is to subscribe to the token stream. For example, if you store token as a stream variable in some service. 
```
export function RestangularConfigFactory (RestangularProvider, authService) {
  RestangularProvider.setBaseUrl('http://api.restngx.local/v1');
  authService.token.subscribe((token) =>
    RestangularProvider.setDefaultHeaders({'Authorization': 'Bearer ${token}'})
  )
}
```
Note: This is not the best option due to pending subscription
