### ISSUE TITLE
Is it possible to change error data from ErrorInterceptor?

### ISSUE THREAD

**Issue by akvaliya** [2muchcoffeecom/ngx-restangular#160]
I have a below code for ErrorInterceptor in angular 7.

```
RestangularProvider.addErrorInterceptor((response, subject, responseHandler) => {
    const error = EnumerableFromObject(response.error.Errors).Select(i => i.Value.Message).FirstOrDefault();
    toastr.error(error, "Error");
    activeRequests--;
    if (!activeRequests) {
      loader.hide();
    }
    **response = error;**
    return true;
  });
}
```

I am getting error like this in error block
`HttpErrorResponse {headers: HttpHeaders, status: 400, statusText: "Bad Request", url: "https://api-dev.medsymphony.com/v1/ProviderNetworkCaregivers", ok: false, …}`

What is i want to return custom error from interceptor. Is it possible? If yes then how?

**Comment by rshchpkn** [comment]
Hi @akvaliya, You can use `subject` to pass handled error to the handler in subscribe method. Here is an example of interceptor:
```
provider.addErrorInterceptor((response, subject: Subject<any>, responseHandler) => {
        const handledErrorResponse = 'handledErrorResponse';
        subject.error(handledErrorResponse);
        return false;
      });
```
