### ISSUE TITLE
How to redirect (use router) to login from interceptor

### ISSUE THREAD

**Issue by akvaliya** [2muchcoffeecom/ngx-restangular#161]
I have below interceptor code in my project 

```
RestangularProvider.addErrorInterceptor((response, subject, responseHandler) => {
    const error = EnumerableFromObject(response.error.Errors).Select(i => i.Value.Message).FirstOrDefault();
    toastr.error(error, "Error");
      return response;
  });
```

Now i want to redirect to login when auth-specific error generates. I have auto-expire session & when session expires it will give specific error in http request. 

So how can i use router in interceptor? so i can redirect to login.

**Comment by rshchpkn** [comment]
You can inject router as a [dependecy](https://github.com/2muchcoffeecom/ngx-restangular#configuring-in-the-appmodule-with-dependency-injection-applied) and the use it to make the redirect
