### ISSUE TITLE
Failed requests stops execution with await

### ISSUE THREAD

**Issue by akvaliya** [2muchcoffeecom/ngx-restangular#164]
I have error interceptor like below

```
RestangularProvider.addErrorInterceptor((response) => {

    const error = EnumerableFromObject(response.error.Errors)
      .Select(i => i.Value.Message)
      .FirstOrDefault();
    toastr.error(error, "Error");

    return true;
  });
}
```

Below is code of my auth service
```
  async Login(login: string, password: string) {
    const sessions = this.rest.all("sessions");
    const params = {Login: login,Password: password };
    const response = await sessions.post(params).toPromise();
    return response;
  }
```

And this is how i am calling it in my component

```
this.loader.show();
const response = await this.authorizationService.Login(login, password);
this.loader.hide();
```

So i have to hide loader after service is completed failed or not.

My issue is when request fails with any reason like wrong credentials execution stops & it never reaches to `this.loader.hide();`

How to handle this without using `then`. In my project all methods are called with `await`. so i can't remove await & use then. It will require so much rework.

Anyone can tell me what am i missing here?

**Comment by victorsosa** [comment]
this is related to the #162 issue

**Comment by rshchpkn** [comment]
@akvaliya Please check @victorsosa solution works for you, if not please notify me so I could reopen this issue.
