### ISSUE TITLE
HttpResponse wrong import

### ISSUE THREAD

**Issue by yerevin** [2muchcoffeecom/ngx-restangular#165]
ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

I see that you already fixed that in repo - can you tell me when you will deploy it to npm? Without that upgrade to angular8 is not possible

**Comment by bostondevin** [comment]
Me too!

**Comment by vpArth** [comment]
Repo looks like abondoned, isn't it?

**Comment by bal3no** [comment]
I made a PR proposal to resolve this issue.
[#174](https://github.com/2muchcoffeecom/ngx-restangular/pull/174)
Waiting for some feedback

**Comment by yerevin** [comment]
You can at this moment install version - 5.0.0-rc1 - it has fix for that issue
