### ISSUE TITLE
Please upgrade to core-js@3.0.0

### ISSUE THREAD

**Issue by yerevin** [2muchcoffeecom/ngx-restangular#166]

**Comment by matthew-green** [comment]
I'm also seeing an error that I'm assuming is related to not being current on core-js
```
ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\path\to\project\node_modules\ngx-restangular\fesm5'
```

**Comment by stbn694** [comment]
Yes, it's currently supporting version 2.5 which is no longer maintained. It would be nice the upgrade to v3.

**Comment by snahmad** [comment]
I have moved to ngx-restangular latest version. Is this resolved.

**Comment by snahmad** [comment]
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\Work\Actisense\W2K1\angular\webApp\node_modules\ngx-restangular\fesm5'

**Comment by bal3no** [comment]
I made a PR proposal to resolve this issue.
[#174](https://github.com/2muchcoffeecom/ngx-restangular/pull/174)
Waiting for some feedback

**Comment by rshchpkn** [comment]
Hi, please check for the solution in #168
