### ISSUE TITLE
ngx-restanular error in angular 8

### ISSUE THREAD

**Issue by kamaruzzaman** [2muchcoffeecom/ngx-restangular#168]
After upgrading my project to Angular 8, I am getting the following error from ngx-restangular:

ERROR in node_modules/ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

It would be nice if you fix the Issue so that ngx-restangular can be used with angular 8

**Comment by kamaruzzaman** [comment]
I have upgraded ngx-restangular to angular 8 in the branch:

https://github.com/kamaruzzaman/ngx-restangular/tree/Issue_168_angular8

**Comment by jc950** [comment]
Is there a merge and an npm publish planned ?

**Comment by tairezzzz** [comment]
working on it

**Comment by jc950** [comment]
Thank you !

**Comment by jcheros** [comment]
> I have upgraded ngx-restangular to angular 8 in the branch:
> 
> https://github.com/kamaruzzaman/ngx-restangular/tree/Issue_168_angular8

After installing from this branch the module import fails:

`import { RestangularModule } from 'ngx-restangular';` -> `error TS2307: Cannot find module 'ngx-restangular'.`

**Comment by hijamoya** [comment]
Same issue here..

**Comment by snahmad** [comment]
Is this fixed.

I am getting as well.
ERROR in node_modules/ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

How get I can updated ngx-restangular.

**Comment by snahmad** [comment]
Any resolution on this issue using with latest angulr 8.

ERROR in node_modules/ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

**Comment by jcheros** [comment]
> Any resolution on this issue using with latest angulr 8.
> 
> ERROR in node_modules/ngx-restangular/lib/ngx-restangular-http.d.ts(3,27): error TS2307: Cannot find module '@angular/common/http/src/response'.

Try with `5.0.0-rc1`

**Comment by snahmad** [comment]
I installed

npm install ngx-restangular@5.0.0-rc1 --save

but now getting different errors.

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/array' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/date' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/function' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/map' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/math' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/number' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/object' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/parse-float' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/parse-int' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/regexp' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/set' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/string' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/symbol' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/weak-map' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\Work\Actisense\W2K1\angular\webApp\node_modules\ngx-restangular\fesm5'

**Comment by jcheros** [comment]
> I installed
> 
> npm install ngx-restangular@5.0.0-rc1 --save
> 
> but now getting different errors.
> 

Maybe you need to update your Angular Cli.
My package.json looks like this

```
"dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/material-moment-adapter": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/pwa": "^0.800.3",
    "@angular/router": "^8.0.0",
    "@angular/service-worker": "^8.0.0",
    "core-js": "2.5.1",
    "ngx-restangular": "5.0.0-rc1",
    "rxjs": "6.5.2",
    "rxjs-compat": "6.3.0",
    "zone.js": "~0.9.1",
    ...
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.2",
    "@angular/cli": "^8.0.2",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "8.0.0",
    ...
    "tslint-language-service": "^0.9.9",
    "typescript": "3.4.5"
  }
```

**Comment by snahmad** [comment]
I have moved to ngx-restangular latest version. 
using now ngx-restangular": "^5.0.0-rc1",
now getting 

Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\Work\Actisense\W2K1\angular\webApp\node_modules\ngx-restangular\fesm5'

**Comment by snahmad** [comment]
any idea?

how to fix it.
Should I move back to angular 6 or 7.

**Comment by bal3no** [comment]
Finally I found a solution to work with ngx-restangular 5.0.0-rc1, angular 8.2.3 and core-js 3.2.1. First of all, to solve the error
`"Can't resolve 'core-js/es7/reflect'"`
I had to change the import in my polyfill.ts to "core-js/es/reflect".

Next, I got a similar error in ngx-restangular
`Module not found: Error: Can't resolve 'core-js/fn/object'` (same as @snahmad)
and had to change the line
`import { assign } from 'core-js/fn/object';` to
`import { assign } from 'core-js/features/object';`
in ngx-restangular/fesm5/ngx-restangular.js

This worked for me ... but how to have the correction inside the ngx-restangular package?

UPDATE: I've made my first try to make a PR ...

**Comment by rshchpkn** [comment]
Hi, thanks to the @bal3no PR I published a new version under `rc` tag. To install use `npm install ngx-restangular@rc`

**Comment by rshchpkn** [comment]
Published `5.0.0` version. Please notify me if there are any issues

**Comment by akvaliya** [comment]
I am getting this error `
ERROR in ./node_modules/ngx-restangular/fesm2015/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/features/object'
`
My project has `"core-js": "^2.6.4"`

**Comment by zzhou718** [comment]
@akvaliya please update your ngx-restangular to 5.0.0 (not 5.0.0-rc1) and core-js to 3.2.1. I saw this issue as well on August 29 and solved it by doing so.

**Comment by soutionscience** [comment]
> I have moved to ngx-restangular latest version.
> using now ngx-restangular": "^5.0.0-rc1",
> now getting
> 
> Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Work\Actisense\W2K1\angular\webApp\src'
> ERROR in ./node_modules/ngx-restangular/fesm5/ngx-restangular.js
> Module not found: Error: Can't resolve 'core-js/fn/object' in 'C:\Work\Actisense\W2K1\angular\webApp\node_modules\ngx-restangular\fesm5'

solved the issue by installing the running npm i core-js@3

**Comment by joaquindiazs** [comment]
Is there still support in this issue for the latest versions of angular?
`
   "ngx-restangular": "^5.0.0-rc3",
`
