### ISSUE TITLE
How to send array in Request Payload ?

### ISSUE THREAD

**Issue by JerimSD** [2muchcoffeecom/ngx-restangular#170]
Hi,

I'm having trouble passing an array of data to my backend application. I'm doing as following :

```
updateCars(cars: Car[]): Observable<Car[]> {
    const carRest = this.restangular.copy(cars);
    carRest.route = 'my-end-point/cars';
    return carRest.put();
}
```

When I do a PUT this way, my `cars` data is sent in the request payload as an object, mapping each element of my array such as :
```
{
  0: {... a car ...},
  1: {... a car ...},
  2: {... a car ...},
  3: {... a car ...}
}
```
where I just want to send an array of cars such as :
```
[
  {... a car ...},
  {... a car ...},
  {... a car ...},
  {... a car ...}
]
```

Can anyone help me achieve this trivial thing ? :slightly_smiling_face:

**Comment by rshchpkn** [comment]
Updating route of the restangular object is not the proper way to change base URL. Consider creating [a separate instance of restangular](https://github.com/2muchcoffeecom/ngx-restangular#decoupled-restangular-service) or use [withConfig](https://github.com/2muchcoffeecom/ngx-restangular#withconfig)
