### ISSUE TITLE
PUT on a sub-property of an element

### ISSUE THREAD

**Issue by Malex** [2muchcoffeecom/ngx-restangular#171]
Hi, I could not find this in the documentation, so I'll ask here.
Is there a way to make a put on a subelement without doing a get first?
I have this situation:

- obj is retrieved at /objs/{objId} 
- status property of obj is set by the user to a new value
- a PUT must be issued to /objs/{objId}/status

Business requirements make mandatory to only do the PUT on the "subelement", a PUT on the whole object would break things (namely object version persistence) outside of our control (sadly). Is this use of rest API supported by restangular?

**Comment by JerimSD** [comment]
Wouldn't the PATCH method be a better fit for your case ?
As the PATCH method purpose is to update only part of an object instead of the whole object.

**Comment by Malex** [comment]
I will check with the client department if a patch can work without triggering their PUT side-effects (that's the issue at hand).
Using the sub-resource URI was a way to circumvent the side effects totally by not entering that endpoint
