### ISSUE TITLE
Error npm install with git branch

### ISSUE THREAD

**Issue by DamienP33** [2muchcoffeecom/ngx-restangular#172]
I try to install the module with git to have the branch **"feat/migrate-to-angular-8**' with the command : `npm install 2muchcoffeecom/ngx-restangular#feat/migrate-to-angular-8`

without success, I have the following error:

> Can't install github:2muchcoffeecom/ngx-restangular#c8b0d4951e7c5a7f70486bf9364e700c3413db5c: **Missing package version**

A solution?

**Comment by jcheros** [comment]
Add it directly in package.json
`"ngx-restangular": "github:2muchcoffeecom/ngx-restangular#feat/migrate-to-angular-8"`

**Comment by DamienP33** [comment]
This way, there is no longer the npm error and there is the folder "ngx-restangular" in node_modules.

But the module remains untoubled for Angular and the compiler!

**Comment by hijamoya** [comment]
try 5.0.0-rc1 for now.

**Comment by DamienP33** [comment]
With '5.0.0.0-rc1' the module is well found.
But I have that mistake now:

> ERROR in ./node_modules/ngx-restangular/fesm2015/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js /fn/object' in '/node_modules/ngx-restangular/fesm2015'
ℹ ｢wdm｣: Failed to compile

**Comment by DamienP33** [comment]
Replacing the line :

`import { assign } from 'core-js/fn/object';`
with
`import { assign } from 'core-js/stable/object/assign';`

In the file : /node_modules/ngx-restangular/fesm2015/ngx-restangular.js

I have no more mistakes !

**Comment by bal3no** [comment]
I made a PR proposal to resolve this issue.
[#174](https://github.com/2muchcoffeecom/ngx-restangular/pull/174)
Waiting for some feedback

**Comment by rshchpkn** [comment]
@DamienP33 released `5.0.0-rc3` using @bal3no PR. Please take a look at #168 issue
