### ISSUE TITLE
Not working with Angular 8

### ISSUE THREAD

**Issue by akvaliya** [2muchcoffeecom/ngx-restangular#178]
I have angular 8 project. 

When i tried to add `ngx-restangular: 5.0.0` it's giving me below error.

`ERROR in ./node_modules/ngx-restangular/fesm2015/ngx-restangular.js
Module not found: Error: Can't resolve 'core-js/features/object'`

**Comment by bal3no** [comment]
You need also to upgrade your core-js version to > 3.0.0
