### ISSUE TITLE
Support type defintions for ngx-restangular

### ISSUE THREAD

**Issue by CharlieUPB** [2muchcoffeecom/ngx-restangular#180]
Is there any type definition file for this library? I think this is insanely necessary, since this is an Angular library and given that Angular promotes using typescript, i think this is needed.

**Comment by rshchpkn** [comment]
Hi @CharlieUPB , We understand the necessity of typings but unfortunately it isn't possible with the current structure of restangular. Mainly because all of its methods can be renamed. Any ideas are appreciated
