### ISSUE TITLE
Should `@types/lodash` be a non-dev dependency?

### ISSUE THREAD

**Issue by jaydiablo** [2muchcoffeecom/ngx-restangular#184]
I noticed on Snyk (https://snyk.io) that this project pulls in `@types/lodash` as a non-dev dependency.

https://github.com/2muchcoffeecom/ngx-restangular/blob/master/projects/ngx-restangular/package.json#L49

This should be moved to the `devDependencies` section right?

**Comment by rshchpkn** [comment]
Hi @jaydiablo, Thanks for your question. It shouldn't be moved to `devDependecies` as in this way it won't be installed when `ngx-restangular` is installed.
