### ISSUE TITLE
Issue with angular beta-4

### ISSUE THREAD

**Issue by zenkkor** [2muchcoffeecom/ngx-restangular#19]
Hey!

I took my repo and did npm install on a different computer and am now getting an error (no code changes, nothing). A package had to have updated that hasnt before. Any help with this would be much appreciated.  

The error is:  

`ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CONFIG_OBJ in /Users/Au/Projects/AU/M/app.io/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol RestangularModule.forRoot in /Users/Au/Projects/AU/mo/app.io/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol AppModule in /Users/Au/Projects/AU/mo/app.io/src/app/app.module.ts, resolving symbol AppModule in /Users/Au/Projects/AU/mo/app.io/src/app/app.module.ts`  

My app.module looks like this:  

```
export function configFunc (RestangularProvider, http) {
  RestangularProvider.setBaseUrl('...');
}

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule,
        TranslateModule.forRoot(),
        SharedModule,

        RoutingModule,
        RestangularModule.forRoot([Http], configFunc)

    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }   
```  

I am using:  
`Angular 4.0.0-beta.4` and   `angular-cli 1.0.0-beta.26`  

Thanks!

**Comment by zenkkor** [comment]
Is this package still not compatible with angular 4? We are at rc.4 now and I would love to use it, but no dice so far. :)

**Comment by tairezzzz** [comment]
@zenkkor team is working on it - my expectation that we will finish next week.

**Comment by zenkkor** [comment]
@tairezzzz thanks for the response. Look forward using it!

**Comment by logvinoleg89** [comment]
Hi @zenkkor, We add version 1.0.0-beta.2, you can install it with tag "beta".

**Comment by Agrumas** [comment]
@logvinoleg89 thanks, works great!

**Comment by zenkkor** [comment]
Thanks @logvinoleg89 - will test it out today! :) Awesome
