### ISSUE TITLE
Should it add query string to route?

### ISSUE THREAD

**Issue by kishorpawar** [2muchcoffeecom/ngx-restangular#194]
I am fetching resource like 
```
accounts = Restangular.all('accounts/?active=true')
```

what should be the case 

**case 1**
```
accounts[0].route = 'accounts/'
```

**case 2**
```
accounts[0].route = 'accounts/?active=true'
```

P.S. the case 2 is breaking `.put()` api.

**Comment by rshchpkn** [comment]
Hi @kishorpawar, Why don't you use Restangular.all('accounts').put(<queryParams>) for your case? If you need any more help please let us know

**Comment by kishorpawar** [comment]
> Hi @kishorpawar, Why don't you use Restangular.all('accounts').put() for your case? If you need any more help please let us know

Thanks @rshchpkn for the reply first of all. 

I assumed `.put()` supposed to be called on single object, right? In case of `Restangular.all('accounts').put()` we need to pass the object to be updated in `.put(object)`, right? 

Somehow when I am doing `.put()` on single object, a `/` is getting appended after the querystring.
