### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by salvadormarcos** [2muchcoffeecom/ngx-restangular#196]
Hello friends,

Is NgxRestangular still being maintained? I ask this because the last release on NPM is from 08/28/2019 and after date we had two releases from Angular (9 and 10).

Analyzing this repository, I found the items below still open. These items, apparently, are easy to solve:
- #181 
- #192
- #195

**Comment by bal3no** [comment]
Hi,
I am trying to contribute to this project, it would be sad to have to give up with this (official) upstream. I've made a PR #199 to resolve some of the older issues and to make it working with Angular 10. Hope they will check it and merge it soon if it's all right.

**Comment by rshchpkn** [comment]
Hi @salvadormarcos @bal3no, Thank you for the contribution and reporting issues. New version is released. Any feedback will be highly appreciated
