### ISSUE TITLE
withCredentials support

### ISSUE THREAD

**Issue by windmaomao** [2muchcoffeecom/ngx-restangular#20]
currently i couldn't make the following work

```  
    RestangularProvider.setDefaultHttpFields({ withCredentials: true });
```

by looking at the request creation,

```
    let requestOptions = new RequestOptions({
```

seems we are missing `withCredentials: true` as one of the options. I just wonder if this is the case, since without it, i couldn't get 'set-cookie' work

**Comment by windmaomao** [comment]
ok, i realized i might made a mistake, I did use the following,

```
  RestangularProvider.setDefaultHttpFields({ withCredentials: true });
```

however I got confused about PUT and customPUT call syntax, what I should do is 

```
  .customPUT(item)
```

The mistake is that I did put(item), which put everything into header.

**Comment by tamascsaba** [comment]
It is a valid issue: https://github.com/2muchcoffeecom/ng2-restangular/blob/0a3d8151d697b4776393596125d9ae12148ce120/src/ng2-restangular-helper.ts#L10-L16 not add withCredentials to RequestOptions.

**Comment by logvinoleg89** [comment]
We have updated Restangular - please check [link](https://github.com/2muchcoffeecom/ng2-restangular#how-can-add-withcredentials-params-to-requests)

**Comment by tamascsaba** [comment]
thx :+1:

**Comment by tairezzzz** [comment]
you're welcome @tamascsaba, thanks for your contribution 👍
