### ISSUE TITLE
problem with RestangularModule.forRoot(RestangularProvider 

### ISSUE THREAD

**Issue by stevermeister** [2muchcoffeecom/ngx-restangular#21]
Trying to do 
`RestangularModule.forRoot((RestangularProvider) => `

from manual and getting error:

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the func
tion or lambda with a reference to an exported function (position 18:31 in the original .ts file), resolving symbol AppModul
e in ..../src/app/app.module.ts
```

**Comment by stevermeister** [comment]
had to do 
```
export function restangularInit(RestangularProvider) {
  RestangularProvider.setBaseUrl('...');
}
```
and after 
```
RestangularModule.forRoot(restangularInit),
```

it would be nice if you check this case and update docs accordingly

**Comment by naviens** [comment]
@stevermeister I am also facing this issue on ionic build android. where need to place the above code. In app.component.ts ??

> [16:36:35]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function (position 20:31 in the original 
            .ts file), resolving symbol AppModule in 
            /home/naveen/workspace/Navi/phonegap/ionicauth2/.tmp/app/app.module.ts 
[16:36:35]  ngc failed 
[16:36:35]  ionic-app-script task: "build" 
[16:36:35]  Error: Error 
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE


Any solution for resolving this issue.

**Comment by mackelito** [comment]
Worked for me as well :) 👍 thx

**Comment by logvinoleg89** [comment]
We have updated documentation - and it in mostly reflects the method used by @stevermeister
