### ISSUE TITLE
ANY everywhere

### ISSUE THREAD

**Issue by yuriykuzin** [2muchcoffeecom/ngx-restangular#23]
any plans to specify strict types?

![image](https://cloud.githubusercontent.com/assets/1729556/22458508/7ba4da76-e7a5-11e6-8bbe-bb5c33d9dada.png)

**Comment by logvinoleg89** [comment]
Yes, we plan to perform this in 2nd version. 
There we also intend to change ng2-restangular to make it more ng2-way.

**Comment by Splaktar** [comment]
Maybe we aren't configuring out typings properly. We're on `2.0.2` and we're still seeing everything listed as `any`. I don't see any custom steps in the docs for installing with Angular v5 though.
