### ISSUE TITLE
Issue with subscription to remove()

### ISSUE THREAD

**Issue by bojanfbm** [2muchcoffeecom/ngx-restangular#25]
I've tried to subscribe to remove() to do some logging after removal of item and refreshing the grid. But I can't subscribe to remove(). It's send DELETE request and remove element from database. I get 200 - OK from server but on client I can't hit subscribe method after that. 

Could you help me somehow? 

This is what I've tried:
`restangular.one('Inventory', id).remove().subscribe( () => { console.log("blah") })`

**Comment by logvinoleg89** [comment]
Hi @bojanfbm, please check  this [link](https://github.com/2muchcoffeecom/ng2-restangular#how-can-i-send-a-delete-without-a-body). I think you'll find the solution there.

**Comment by bojanfbm** [comment]
@logvinoleg89  Thank you very much, I will check it out.

**Comment by cadin81** [comment]
I've noticed that if I return an object from the server (JSON) on the POST / DELETE call, the subscribe() callback is called. Otherwise it won't work. I've tried the mentioned workaround:

RestangularProvider.setRequestInterceptor(function(elem, operation) {
  if (operation === "remove") {
     return null;
  }
  return elem;
})

But it didn't do for me.

**Comment by cadin81** [comment]
Since the problem was in the response (which is waiting for an object to return), I got the idea of the interceptor and used the response interceptor instead:

      RestangularProvider.addResponseInterceptor((data, operation, what, url, response) => {
        switch (operation) {
          case 'post':
          case 'put':
          case 'remove':
            if (!data)
              return {};
          default:
            return data;
        }
      });

That implementation worked for me. :-)

**Comment by logvinoleg89** [comment]
Hi @cadin81, @bojanfbm we updated Restangular. Now we handle it in default response interceptor.
