### ISSUE TITLE
FAQ - Processing Errors with Observables

### ISSUE THREAD

**Issue by focher** [2muchcoffeecom/ngx-restangular#26]
Currently the FAQ has the following code to handle errors from REST calls.

```
Restangular.all("accounts").getList().subscribe( response => {
  console.log("All ok");
}, errorResponse {
  console.log("Error with status code", errorResponse.status);
});
```

The code is missing the **=>** for the errorResponse. It should read:

```Restangular.all("accounts").getList().subscribe( response => {
  console.log("All ok");
}, errorResponse => {
  console.log("Error with status code", errorResponse.status);
});
```

Thanks for the project, by the way! Really great!

**Comment by logvinoleg89** [comment]
@focher thanks for pointing that our - will fix that shortly. 
And thanks for your appreciation :)
