### ISSUE TITLE
Subscribe on put and save doesn't work

### ISSUE THREAD

**Issue by ccpony** [2muchcoffeecom/ngx-restangular#27]
angular: 2.4.1 
ng2-restangular: ^0.1.28

The following code calls the put successfully, but neither code blocks (success or fail) are called.

```
    this._accountService.account.put().subscribe( <- this works, the record is saved to the db
      (res) => {
        this._notifier.success("Saved","Account was successfully saved.");  <- not called on success
        this._router.navigate(['/references/accounts']); <- not called on success
      }, 
      (err) => {
        this._notifer.error("Server Error", 'Account was not saved: ' + err); <- not called on error
      }
```

How do you do error checking on put or save calls?  I haven't tested this with post.

Thank you for this incredible tool.

**Comment by logvinoleg89** [comment]
this._accountService.account - is this a restangular object?
What does server respond you: do you get an empty response or are there some data in it?
Please check my comment here #25 - maybe it will be helpful.

**Comment by ccpony** [comment]
this._accountService.account = new Restangular(Account, null, null);

Walking through the running code on the browser, the subscribe method is skipped altogether.  The subscribe block is simply stepped over.  Does put() even implement subscribe?  I've yet to find even a single example in any of the tutorials or demos that implements put().subscribe.

Thanks!

edit: I checked out your link.  I don't see the correlation.  I am new at Restangular, however.  More guidance would be greatly appreciated.

**Comment by cadin81** [comment]
I've noticed that if I return an object from the server (JSON) on the POST / DELETE call, the subscribe() callback is called. Otherwise it won't work. I've tried the mentioned workaround:

RestangularProvider.setRequestInterceptor(function(elem, operation) {
if (operation === "remove") {
return null;
}
return elem;
})

But it didn't do for me.

**Comment by cadin81** [comment]
Since the problem was in the response (which is waiting for an object to return), I got the idea of the interceptor and used the response interceptor instead:

      RestangularProvider.addResponseInterceptor((data, operation, what, url, response) => {
        switch (operation) {
          case 'post':
          case 'put':
          case 'remove':
            if (!data)
              return {};
          default:
            return data;
        }
      });

That implementation worked for me. :-)

**Comment by ccpony** [comment]
Thanks.  But excuse me for asking - - is that really the way it's supposed to be?  Why should there be a work-around for such an obvious task such as making a put() call and returning an observable?

Please explain.  I must be missing something very obvious here.

**Comment by cadin81** [comment]
I do agree that the workaround shouldn't be necessary. I believe the subscribe callback should be called even if no JSON object is returned. I think Restangular should consider only the HTTP status returned, but maybe I'm missing something too.

**Comment by ccpony** [comment]
Must say, cadin81, that this is very confusing to me.  Ng2-restangular has 300 github stars and yet put() doesn't seem to work properly.  I don't know how that's possible.  Perhaps the documentation is just poor in this area or maybe it's just a serious bug.  Really need to hear from one of the main developers here.  Thanks.

**Comment by rshchpkn** [comment]
@cadin81 @ccpony If server doesn`t respond with an object, you will never get emit in your subscribtion. Please check documentation of [RxJS](http://reactivex.io/documentation/observable.html) this may help you with it

**Comment by ccpony** [comment]
rshchpkn - what is best practice for testing whether a put() was successful and taking action on that success or failure response?

**Comment by logvinoleg89** [comment]
Hi @ccpony, we updated Restangular. Now you always get emit in subscribe even when server responses with no content.

**Comment by ccpony** [comment]
Excellent!
