### ISSUE TITLE
About the SHOULD contain a array business :)

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#28]
Most of the API´s I have been using lately all deliver a json object at the top level
Readning here: http://jsonapi.org/format/#fetching
we can see the following statement:

> A JSON object MUST be at the root of every JSON API request and response containing data. This object defines a document’s “top level”.

But when using restangular it states that it should be an array.. why is that?
I´m not saying that this is wrong.. just want to understand why.

Note: I already use RestangularProvider.addResponseInterceptor to handle this for me so I have no real issue.

**Comment by logvinoleg89** [comment]
Hi @mackelito, this is the restangular "inheritance" and there were no reasons to change it.

**Comment by mackelito** [comment]
@logvinoleg89 do you know the reasoning behind it? Why it was decided to do it this way?
Perhaps we should revise it and see if it should be changed to match jsonapi?

**Comment by logvinoleg89** [comment]
Hi @mackelito,  we have considered this but it can be performed not earlier than in the next ng2-restangular version.
