### ISSUE TITLE
toPromise promise is never resolved

### ISSUE THREAD

**Issue by qazwsxedcrfvtgb1111** [2muchcoffeecom/ngx-restangular#29]
An Observables promise is resolved when the observable is complete, but that doesn't appear to ever happen.

**Comment by logvinoleg89** [comment]
Hi @qazwsxedcrfvtgb1111, could you give more details for us? Maybe share your code?

**Comment by qazwsxedcrfvtgb1111** [comment]
Sure, here's a modified version of your demo app:
http://embed.plnkr.co/4AjmnZb7ay7bFKpyBbwh/
The changes are to src/heroapp/hero-list/hero-list.component.ts
The expected behavior is for the promise to be resolved, and the hero list to be updated, instead it is never resolved.

**Comment by logvinoleg89** [comment]
Hi @qazwsxedcrfvtgb1111, please update ng2-restangular to the latest version (0.1.30)
