### ISSUE TITLE
issue on set session in header

### ISSUE THREAD

**Issue by sureshhustle** [2muchcoffeecom/ngx-restangular#30]
Hi,
   I am using restangular in my project, i jjust set that global restangular factory in app.module it will load first time when my home page loads. but after logged in in it will not refresh the restangular after set the session key, its only display session token as empty and display after reload the page.
please help me to solve that issue

**Comment by logvinoleg89** [comment]
You can use RequestInterceptor. Look example above: 
````
export function RestangularFunction(RestangularProvider, authService, store) {
  // set default static headers
  RestangularProvider.setDefaultHeaders({Authorization: `default token`});
  
  RestangularProvider.addFullRequestInterceptor((element, operation, path, url, headers, params)=> {
    // set token to every request
    return {
      headers: Object.assign({}, headers, {
        Authorization : `Bearer ${authService.jwt}`
      }),
    }
  });
}
````

**Comment by mackelito** [comment]
Hey!
I´m having a similar issue and was hoping you could help me out! :)

```javascript
  RestangularProvider.addFullRequestInterceptor((element, operation, path, url, headers, params) => {
      // set token to every request
      console.log({AuthService});
      return {
        headers: Object.assign({}, headers, {
          Authorization : `Bearer ${AuthService.access_token}`
        }),
      }
    });
```
console.log({AuthService}) gives me `Object {AuthService: undefined}`
and "${AuthService.access_token}" give me `Cannot read property 'access_token' of undefined`

Not sure what to look for  here :)

**Comment by ranwahle** [comment]
When importing the restangular module use 

RestangularModule.forRoot([AuthService], RestangularConfigFactory),
