### ISSUE TITLE
Observable failure

### ISSUE THREAD

**Issue by RodolfoSilva** [2muchcoffeecom/ngx-restangular#31]
When I call the `.getList` method, when it finishes executing it doesn't call the method `Observable.finally`.

```javascript
 Restangular
  .one("accounts",123)
  .one("buildings", 456)
  .all("spaces")
  .getList()
  .finally(() => console.log("Done!"))
  .subscribe((users) => console.log(users));
```

**Comment by qazwsxedcrfvtgb1111** [comment]
Yup, this is the same issue I'm having
https://github.com/2muchcoffeecom/ng2-restangular/issues/29

**Comment by mackelito** [comment]
Any updates on this?

**Comment by RodolfoSilva** [comment]
No, I decided to write a new Restangular with TypeScript https://github.com/RodolfoSilva/rs-restangular

**Comment by tairezzzz** [comment]
@RodolfoSilva We will appreciate any help with this issue, but I don't think this is right place to promote your own project :) Thanks for your patience :1st_place_medal:

**Comment by tairezzzz** [comment]
@mackelito @qazwsxedcrfvtgb1111 I'll try to check it tomorrow, guys! Thanks for using it 👍

**Comment by tairezzzz** [comment]
Looks like we got some result on this one - needs additional testing. Will update tomorrow.

**Comment by RodolfoSilva** [comment]
Sorry, but it was not my intention to promote the project. I only divulged my solution.

**Comment by tairezzzz** [comment]
Got it :) Let's reach out tomorrow when we'll have solution for this.

**Comment by logvinoleg89** [comment]
Hi @qazwsxedcrfvtgb1111, @mackelito, please update ng2-restangular to the latest version (0.1.30)
