### ISSUE TITLE
model in services to decouple restangular

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#33]
I want to create services to fetch products from a api and then map it to my own product model to make it easy to switch between different API´s

This is the current service:
```javascript
getProducts(category) {
      let products = this.restangular.all("products").customGET();
  }
``` 

So that´s simple and works. Now I would like to map the response data to match my product model.
What approach would you recommend?

**Comment by RodolfoSilva** [comment]
Use `.map((res) => Model.fromJSON(res))`. You will need implement `fromJSON` static method.

**Comment by mackelito** [comment]
Yeah that is actually what I ended up doing... kind of.. :)

```javascript
  let productList = response.result.map( product => {
          product = {
            'id' : product.id,
            'title' : product.title,          }
          return product;
        });
        return productList;
```
