### ISSUE TITLE
How to access service in export function restangularInit

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#37]
I have a service (AuthService) that I need to access in my restangularInit function (in my app.module.ts) but I dont know how I cant get access to it.

```javascript
import { BrowserModule } from '@angular/platform-browser';
    import { NgModule } from '@angular/core';
    import { FormsModule } from '@angular/forms';
    import { HttpModule } from '@angular/http';
    import { MaterialModule } from '@angular/material';
    import { FlexLayoutModule } from "@angular/flex-layout";
    import { RestangularModule } from 'ng2-restangular';

    // Components
    import { AppComponent } from './app.component';
    import { ProductComponent } from './components/product/product.component';

    // Services
    import { AuthService } from './services/auth.service';

    export function restangularInit(RestangularProvider, AuthService) {
      console.log(AuthService); // this is undefined
      let token = AuthService.getToken(); //This is what I want to do
      RestangularProvider.setBaseUrl('api');
      RestangularProvider.setDefaultHeaders(
        {'Authorization': 'Bearer ' + token},
      );
    }

    @NgModule({
      declarations: [
        AppComponent,
        ProductComponent
      ],
      imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        MaterialModule,
        FlexLayoutModule,
        RestangularModule.forRoot(restangularInit)
      ],
      providers: [
        AuthService
      ],
      entryComponents: [ProductComponent],
      bootstrap: [AppComponent]
    })
    export class AppModule { }
```

**Comment by timaxapa** [comment]
Hi @mackelito . You closed issue - does it mean you found a solution to inject something to initializer?

**Comment by mackelito** [comment]
@timaxapa Yeah it was just a matter of injecting it...

`    RestangularModule.forRoot([MyService], restangularInit),`

**Comment by timaxapa** [comment]
@mackelito Hah, I tried this code but got an error
`EXCEPTION: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded`
My AuthService has a restangular dependency in the constructor ) Other services injects perfectly. Thanks!

**Comment by TolotraRam** [comment]
@timaxapa don't import Restangular inside MyService try to use Angular Http

**Comment by timaxapa** [comment]
@TolotraRam Hm, In this case - why I need restangular? I use it instead of working with native Http

**Comment by tairezzzz** [comment]
@timaxapa Looks like you should revise your current architecture to use DI properly.

**Comment by timaxapa** [comment]
@tairezzzz Yes, you are right. I shouldn't pass service requires Restangular to Restangular as DI ) There is no problem now, thanks for your answer.

**Comment by mackelito** [comment]
@timaxapa please explain how you solved it for others to learn from 👍

**Comment by timaxapa** [comment]
I got answer in [comment](https://github.com/2muchcoffeecom/ng2-restangular/issues/37#issuecomment-287696535)

**Comment by mibeon** [comment]
How was the problem solved?
The comment link isn't active anymore.

Please, help me guys!
