### ISSUE TITLE
How to set Bearer token

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#38]
I have a service where I have a getToken() method.
getToken uses localforage to get it form localstorage (https://localforage.github.io/localForage/#data-api-getitem)

    getToken() {
      return localforage.getItem('auth', function (err, value) {
        return _.result(value, ['access_token']);
      });
    }

But I have the problem where the componets I have makes requests before the token is set.
I have tried to use RestangularProvider.addFullRequestInterceptor but have the same issue there.

So what is the proper way to first get the token from the API and then set it to the defaultHeaders?

**Comment by logvinoleg89** [comment]
Hi @mackelito, you can use addFullRequestInterceptor method. I have updated documentation, please follow [link](https://github.com/2muchcoffeecom/ng2-restangular#i-need-to-send-authorization-token-in-every-restangular-request-how-can-i-do-this)

**Comment by mackelito** [comment]
I solved this by setting up a AuthGuard instead... perhaps that was a bad approach?

**Comment by logvinoleg89** [comment]
In my opinion it's better to use AuthGuard by its initial purpose white to set Bearer token I would use  addFullRequestInterceptor method.
