### ISSUE TITLE
How to return observable response (CustomGET) for resolver? 

### ISSUE THREAD

**Issue by IuriiKryventsov** [2muchcoffeecom/ngx-restangular#39]
Hi, guys! I need some help! In my previous project i used Http provider out of box and all was good, but now i'm encountered with some problems. 

I tried to do request, for example: 
`this.restangular.one('countries').customGET().map((response: any) => response);` 

But it return AnonymousSubject. 
![image](https://cloud.githubusercontent.com/assets/8921054/23669758/098ddd36-036e-11e7-806d-103d80cb06f6.png)

When i used standard Http provided by Angular 2 for get requests it returns Observable like this one:
![image](https://cloud.githubusercontent.com/assets/8921054/23669801/29e4d166-036e-11e7-8ca0-c66a40c9b9f7.png)

How can i do CustomGET request that return Observable object?  

Thanks for help and sorry for my bad English :)

**Comment by logvinoleg89** [comment]
Hi @IuriiKryventsov, please check the latest comment #12 to find the reason for Subject usage.
Please, let us know what issues do you face with Subject usage?

**Comment by IuriiKryventsov** [comment]
@logvinoleg89 yep, because, resolver is expecting Promise or Observable and i'm forced to create Observable from Subject.

**Comment by tairezzzz** [comment]
@IuriiKryventsov It's a requirement of current architecture (Promises legacy), so you have to convert Subject to Observable if you need it.

**Comment by IuriiKryventsov** [comment]
@tairezzzz ok, thx for the answer
