### ISSUE TITLE
cache: true not working

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#40]
When setting  `RestangularProvider.setDefaultHttpFields({cache: true});` it still does the requests to the server when navigating the routes

**Comment by logvinoleg89** [comment]
Hi @mackelito, to perform requests to the server ng2-restangular uses the class [RequestOptions](https://angular.io/docs/ts/latest/api/http/index/RequestOptions-class.html) that doesn't have cache parameter. Currently by setDefaultHttpFields method you can use only withCredentials parameter.

**Comment by mackelito** [comment]
So what is expected to be cached?

**Comment by logvinoleg89** [comment]
In future we'll most likely add the ability to cache requests. For now the developers have to watch the requests not to be repeating if they were already sent.

**Comment by mackelito** [comment]
So there is no caching then.. perhaps there is a good idea to make a note of that in the docs? :)
