### ISSUE TITLE
How to use ErrorInterceptor with http query?

### ISSUE THREAD

**Issue by baidario** [2muchcoffeecom/ngx-restangular#41]
How call new http query when ErrorInterceptor occur(to refresh my token) and then call again query which called ErrorInterceptor?

**Comment by logvinoleg89** [comment]
Hi @baidario, we have updated ErrorInterceptor documentation. Now you can check how to update Authorization header in function addErrorInterceptor by following this [link](https://github.com/2muchcoffeecom/ng2-restangular#adderrorinterceptor)
