### ISSUE TITLE
Testing with Angular-Seed

### ISSUE THREAD

**Issue by calhemp** [2muchcoffeecom/ngx-restangular#42]
Hi, sorry for brother, I'm new in angular 2,  but  anyone test ng2-restangular with angular-seed starter? its a good start
https://github.com/mgechev/angular-seed 

I have the following error at module import

> 02:17:27.556 "(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/rxjs.js
> 	patchProperty/desc.set/wrapFn@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489194053152:1190:26 [<root>]
> 	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489194053152:166:28 [<root> => <root>]
> 	ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489194053152:416:28 [<root>]
> 	
> 	Error loading http://localhost:5555/node_modules/rxjs.js as "rxjs" from http://localhost:5555/node_modules/ng2-restangular/dist/umd/ng2-restangular.js" "Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues" 1 localhost:5555:65:7
> 	<anónimo> http://localhost:5555/:65:7
> 	ZoneDelegate.prototype.invoke http://localhost:5555/node_modules/zone.js/dist/zone.js:330:17
> 	Zone.prototype.run http://localhost:5555/node_modules/zone.js/dist/zone.js:126:24
> 	scheduleResolveOrReject/< http://localhost:5555/node_modules/zone.js/dist/zone.js:679:52
> 	ZoneDelegate.prototype.invokeTask http://localhost:5555/node_modules/zone.js/dist/zone.js:363:17
> 	Zone.prototype.runTask http://localhost:5555/node_modules/zone.js/dist/zone.js:166:28
> 	drainMicroTaskQueue http://localhost:5555/node_modules/zone.js/dist/zone.js:529:25
> 	ZoneTask/this.invoke http://localhost:5555/node_modules/zone.js/dist/zone.js:420:25

it seems that rxjs is not loaded in his real path... when loads

I don't know, if is related to a issue of the project or how this project imports rxjs or SystemJs configuration, or a mistake myself but
in other project seems to be fixed replacing  
import { Observable, BehaviorSubject } from "rxjs"; 
with
import { Observable, BehaviorSubject } from "rxjs/Rx";
https://github.com/xmaestro/angular2-recaptcha/issues/31#issuecomment-249782711

 I tryid other modules as angular2-toaster, ng2-breadcrumbs and works well with seed starter, but this not.

I'd be great if restangular could works with this angular-seed as is very popular, or any hint for try to make works.

thanks, I thanks for this project restangular with angular 2

**Comment by logvinoleg89** [comment]
Hi @calhemp. We applied angular-seed-advanced that is the fork from angular-seed. The rxjs issue was solved by changing tools/config/seed-advanced.config.ts file
````typescript
// Advanced seed packages
let additionalPackages: ExtendPackages[] = [
…
      {
        name: 'rxjs',
        packageMeta: {
          main: `./Rx.js`,
          defaultExtension: 'js'
        }
      },
...
]
````

**Comment by calhemp** [comment]
thanks, is working now, based in this, I finnaly added in this section of angular-seed
seed.config.ts

```
SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    paths: {
...
      'ng2-restangular': 'node_modules/ng2-restangular/dist/esm/src',
      'rxjs': 'node_modules/rxjs/bundles/Rx.js',
 ...
  
    },
    packages: {
      rxjs: {
        main: "./Rx.js",
        defaultExtension: 'js'
      },
     "ng2-restangular": {
        main: './index',
        defaultExtension: 'js'
      },
    }
  };
```

and works good, thanks @logvinoleg89
