### ISSUE TITLE
.get/.customGET and FormData

### ISSUE THREAD

**Issue by IuriiKryventsov** [2muchcoffeecom/ngx-restangular#43]
Hi, guys! Today i've been stuck with next moment: when i used .post() method with formData (i`m creating FormData object through URLSearchParams adapter) all has been ok, but when i'm trying to pass formData object to queryParams in .get() or .customGET() method it doesn't work in expected way and i have my URLSearchParams adapter in query params. 

For example: 
i need to do some request with next filters: 
filter[type] = 1
filter[currency] = 1

**Comment by logvinoleg89** [comment]
Hi @IuriiKryventsov, you need to pass parameters as object.
