### ISSUE TITLE
browser says 401, restangular says 0

### ISSUE THREAD

**Issue by mackelito** [2muchcoffeecom/ngx-restangular#44]
I want to run some functions if I get a 401.
in my code I get response.status as "0" when the browser returns a 401..

`
  RestangularProvider.addErrorInterceptor((response, subject, responseHandler) => {
    console.log(response);
    if (response.status === 401) {
      console.log('401');
    }
  });
`

**Comment by tairezzzz** [comment]
@mackelito, please give me details to simulate request: endpoint url and method. I know one case when Restangular return response status 0 - server is down.

**Comment by mackelito** [comment]
The endpoint is "https://api.moltin.com/v2/carts/1" method is get

**Comment by tairezzzz** [comment]
Server returns status "false" https://screencast.com/t/QU1SDjS4

**Comment by mackelito** [comment]
Please console.log the response

**Comment by tairezzzz** [comment]
Can you add my URL(http://localhost:8000) to avoid CORS https://screencast.com/t/G6oUNzza

**Comment by tairezzzz** [comment]
Looks like problem in CORS, got 0 when removing my server from allowed

**Comment by mackelito** [comment]
@tairezzzz I think there was an issue on moltins end.. it´s working now 🥇 
Thx for you fast replies!!
