### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by mlakhara** [2muchcoffeecom/ngx-restangular#45]
Hi

I wish to start contributing to the package in any ways I can. I also created a fork of the repository and tried to use that in my project (But that didn't work). It would be great if we can publish some guideline on how to contribute (with build steps) so that people like me can go ahead and help you in the awesome stuff that you are doing. :-)

Specifically, the first thing that I wish to start with is typings.

**Comment by ashgibson** [comment]
This would be great to have added to the project. There is already a lib for ng1 restangular which might be a good starting point - https://www.npmjs.com/package/@types/restangular
