### ISSUE TITLE
Question about model classes

### ISSUE THREAD

**Issue by mikesnare** [2muchcoffeecom/ngx-restangular#48]
Is there any support for using ng2-restangular with existing TypeScript model classes?

Say I already have TypeScript model classes for things like Account and User and I would like to use restangular to manage the server interaction but still use my existing models.  Is that possible, or is it planned if it's not?

I'd love to use restangular (I used the old one for a while with angular 1.x and loved it) but not being able to use my own model classes would be a blocker.

**Comment by logvinoleg89** [comment]
Hi @mikesnare, we haven't considered this possibility before but thanks for outlining it. We'll think about adding this feature.

**Comment by ashgibson** [comment]
You can use the extendModel function to map restangular models to your own.

**Comment by ntrpnr** [comment]
@ashgibson Can you elaborate on this? How can I easily use extendModel to user my own models?
