### ISSUE TITLE
Angular 4 - OpaqueToken issue

### ISSUE THREAD

**Issue by baidario** [2muchcoffeecom/ngx-restangular#49]
I tried to update my app to angular 4 and OpaqueToken issue occurred.
`ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CONFIG_OBJ in /home/baidario/Projects/insta-clone/frontend/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol RestangularModule.forRoot in /home/baidario/Projects/insta-clone/frontend/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol AppModule in /home/baidario/Projects/insta-clone/frontend/src/app/app.module.ts, resolving symbol AppModule in /home/baidario/Projects/insta-clone/frontend/src/app/app.module.ts`

Here is my app.module.ts file:

```
export function RestangularConfigFactory(RestangularProvider, http, router) {
  RestangularProvider.setBaseUrl('http://127.0.0.1:3000');
  RestangularProvider.setDefaultHeaders({ 'Content-Type': 'application/json' });

  RestangularProvider.addFullRequestInterceptor(
    (element, operation, path, url, headers, params) => {
      const token = localStorage.getItem('token');
      return { headers: Object.assign({ }, headers, { 'Authorization': `JWT ${token}` }) }
    }
  );
};

@NgModule({
  declarations: [ ... ],
  imports: [
    ...
    RestangularModule.forRoot([Http, Router], RestangularConfigFactory)
  ],
  providers: [ ... ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

Will you migrate your module to angular 4?

**Comment by tairezzzz** [comment]
Please take a look at #19

**Comment by tairezzzz** [comment]
You can insta

**Comment by baidario** [comment]
Oops, sorry. Thanks for your answer
