### ISSUE TITLE
no provider for http error

### ISSUE THREAD

**Issue by fagundes** [2muchcoffeecom/ngx-restangular#5]
I'm using the lastest version of angular2 with ng2-restangular. 

This is related with this [question in StackOverflow](http://stackoverflow.com/questions/40639162/using-angular2-typescript-and-restangular2-no-provider-for-http-error).

`     Error: No provider for Http!`

This ocourrs when I try to inject restangular in any component/page.

```javascript
import {Restangular} from "ng2-restangular";

@Component({
    selector: 'my-app',
    template: require('./app.component.html')
})

export class AppComponent implements OnInit {
    constructor(private restangular: Restangular) {
    }

    ngOnInit() {
        // GET http://api.test.local/v1/users/2/accounts
        this.restangular.one('users', 2).all("accounts").getList();
    }
}
```

**Comment by tairezzzz** [comment]
We fixed it in a last version 0.1.9. Please update to this one! 

Thanks!
