### ISSUE TITLE
Observable and Http errors

### ISSUE THREAD

**Issue by timaxapa** [2muchcoffeecom/ngx-restangular#50]
Can anybody explain me the mechanism of error handling? For example, I have 2 subscribers on one observer

      let observable = this.authService.signIn(formGroup.value.email, formGroup.value.password);
      
      // 1st subscriber
      observable.subscribe((response: SignInResponse) => {
        console.log('First - Success');
      }, () => {
        console.log('First - Error');
      }, () => {
        console.log('First - Finally');
      });
      
      // 2nd subscriber
      observable.subscribe((response: SignInResponse) => {
        console.log('Second - Success');
      }, () => {
        console.log('Second - Error');
      }, () => {
        console.log('Second - Finally');
      });`

If I get 400 from the server - both error messages First - Error, Second - Error appears as expected,
but if I remove error and finally callback for the first subscriber as

      let observable = this.authService.signIn(formGroup.value.email, formGroup.value.password);
      
      observable.subscribe((response: SignInResponse) => {
        console.log('First - Success');
      });

      observable.subscribe((response: SignInResponse) => {
        console.log('Second - Success');
      }, () => {
        console.log('Second - Error');
      }, () => {
        console.log('Second - Finally');
      });

I don't get the error callback of the second subscriber

**Comment by mackelito** [comment]
Could you recreate in a plunkr?

**Comment by timaxapa** [comment]
@mackelito [plunker](https://embed.plnkr.co/Bb3n93U4WdUxPHlganqN/)
Open debugging console. By default, you will get both error messages, but if you remove error and finally callbacks for 1st subscriber - you also will not get an error message from the 2nd subscriber.  I am a newbie in Rx programming, maybe I have a logic mistake in my code

**Comment by mackelito** [comment]
in the service returning the object (this.restangular.one('posts/a')) instead of the result
https://plnkr.co/edit/UhfG7PTTuiBz5D60hgPm?p=preview

Note: updated my replay.. of course you can use the get() method :)

**Comment by timaxapa** [comment]
But in this case, we have two requests to the server. I can explain what I want. I have AuthService with SignIn method and SignInComponent. In component after submitting the form, I do request with AuthService and got a result as Observable. Then I need to save token I get. I want to save token in my service and return observable to component
In service
`signIn(email: string, password: string): Observable<SignInResponse> {
    let observable$ = this.restangular.one(this.url).post('signIn', new SignInModel(email, password));
    observable$.subscribe(res => {
      // save token to localStorage
    });
    return observable$;
  }`

In component
`this.authService.signIn(formGroup.value.email, formGroup.value.password)
        .subscribe((response: SignInResponse) => {
         // redirects, etc
        });`
But, If request returns error, Component subsriber doesn't work

**Comment by mackelito** [comment]
hmmm.. not sure if I follow...
The issue is that you need to authenticate if you don´t have a valid token right?..

I did a solution for this exact senario just a few weeks ago... I ended up using canActivate/AuthGuard and it worked perfectly! :)

**Comment by timaxapa** [comment]
No ) I just want to have 2 subscribers on one request result: 1st in my service to save token, and 2nd in my component to redirect from sign in form.

**Comment by mackelito** [comment]
so the senario is that you have a login component.. and once the user has submitted the form and has gotten the token you want to do a redirect.

So the service will have a login() method that you subscribe to and based on the response you get back you want to redirect if login was successful.. correct?

The service should not have .subscribe() it should return the observable that the component subscribes to.

If you need to store the token in localstorage you can do that in the service.. Here is an example.

    authenticate(): Observable<boolean> {
      console.log('running authenticate()')
        const data =
          'grant_type=' + 'implicit' +
          '&client_id=' + 'WjFdWnyzE44pDUQXV1hLbawrgLYIP2ZanT6C8Cr6ri'

    return this.http.post(this.authUrl, data, { headers: this.headers })
      .flatMap((response: Response) => {
        return localforage.setItem('auth', response.json()).then(res => {
          this.token = _.get(res, ['access_token'])
          this.tokenExpires = _.get(res, ['expires'])
          return !_.isUndefined(this.token)
        })
      })
    }

**Comment by mackelito** [comment]
I´m using http instead of restangular here because of this issue, https://github.com/2muchcoffeecom/ng2-restangular/issues/14#issuecomment-272466188

**Comment by timaxapa** [comment]
Yes, it will work. Thanks for your answer. Issue can be closed
