### ISSUE TITLE
Typings Typings Typings

### ISSUE THREAD

**Issue by dreadbeard** [2muchcoffeecom/ngx-restangular#53]
Would be amazing to have more verbose typings for this library due to Restangular's unique method chaining as well as other things.

**Comment by logvinoleg89** [comment]
Hi @dreadbeard, completely agree. Typings are already included into the list of ng2-restangular improvements.

**Comment by Splaktar** [comment]
@logvinoleg89 where is this list of improvements? I would love to have something better than this...
```typescript
    ...
    customPUT: any;
    customPATCH: any;
    customPOST: any;
    customDELETE: any;
    customGET: any;
    ....
```
