### ISSUE TITLE
POST with number response

### ISSUE THREAD

**Issue by vincent314** [2muchcoffeecom/ngx-restangular#55]
Hi,

My POST service response is just a number (ie `1234`). When I use restangular *post* method, I get an error `Cannot create property ‘route’ on number ’1234’`. I assume that Restangular tries to _decorate_ a Javascript number and fails.

Is a number a valid response for a REST service and should Restangular be fixed for this kind of response ? If I fix the service and return nothing, Restangular post method works perfectly. Should I stick on this solution ?

*Restangular 0.1.30*
*angular 2.4.10*

**Comment by logvinoleg89** [comment]
Hi @vincent314, number is not a valid response. Restangular expect JSON Objects in response
