### ISSUE TITLE
correction in read me page @ 

### ISSUE THREAD

**Issue by moorthi07** [2muchcoffeecom/ngx-restangular#56]
Hope this makes the instructions   better,
Breaks ,
Cannot find name 'Restangular'
at,
 constructor(  private restangular: Restangular) { }

Add this line in the component, 
import { Restangular } from 'ng2-restangular';

Pl. add this line in read me guide. (The demo tutorial has it right)

**Comment by logvinoleg89** [comment]
Thanks @moorthi07, we update  [Quick Configuration](https://github.com/2muchcoffeecom/ng2-restangular/blob/master/README.md#quick-configuration-for-lazy-readers)
