### ISSUE TITLE
Restangular.service() results on an incomplete object

### ISSUE THREAD

**Issue by carlosthe19916** [2muchcoffeecom/ngx-restangular#58]
Calling Restangular.service results on **an object who has just getList(), one(), and post()** methods. Shouln't it results on a complete Restangular object with getList(), one(), and post(), get(), all(), remove() methods?

`var Cars = Restangular.service('cars', Restangular.one('users', 1));`

_Cars value:_
`{
 getList(),
 one(),
 post()
}`

**Comment by logvinoleg89** [comment]
Hi @carlosthe19916. We've added some new methods for this purpose, but since we renamed project you have to remove dependency from ng2-restangular and install ngx-restangular
