### ISSUE TITLE
Error on new Ionic 2 RC3 with AoT compiler

### ISSUE THREAD

**Issue by Xepe** [2muchcoffeecom/ngx-restangular#6]
Hello, 

I am trying to use it with Ionic 2, I got the following error in the ionic build android command. 

> Error: Error encountered resolving symbol values statically. Function calls are not supported. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 7:10 in the original .ts file), resolving symbol RestangularFactory in .. /node_modules/ng2-restangular/dist/esm/src/ng2-restangular.config.d.ts, resolving symbol RestangularModule in .. node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts

Regards.

**Comment by tairezzzz** [comment]
Hey, Xepe, sorry for late response. We will be working on this issue later this week, and will give you some kind of example how to use this project with Ionic 2.

**Comment by tairezzzz** [comment]
@Xepe Thanks for patience, looks like we've fixed it - update will be tomorrow, testing it now 8-)

**Comment by tairezzzz** [comment]
Hey new version "0.1.22" is dev but you can try it yourself. You can install it with "--tag dev" option. Waiting for your feedback.

**Comment by Xepe** [comment]
Thanks for your comments, I had been offline the last 2 days... I will do the test and I will let you know.

**Comment by Xepe** [comment]
:) thanks for you job and help @tairezzzz , I installed the version 0.1.22 and the build is working correctly !

**Comment by tairezzzz** [comment]
@Xepe You're welcome! Thanks for using this project.

**Comment by hemnath11** [comment]
[10:25:22]  Error: Error encountered resolving symbol values statically. Functio
n calls are not supported. Consider
            replacing the function or lambda with a reference to an exported fun
ction (position 40:29 in the original
            .ts file), resolving symbol AppModule in  /.tmp/app/app.module.ts
[10:25:22]  ngc failed
[10:25:22]  ionic-app-script task: "build"
[10:25:22]  Error: Error

I got this error after ng2-restangular installed..

**Comment by tairezzzz** [comment]
hey @hemnath11 Did you try to install it with "--tag dev" option?

**Comment by hemnath11** [comment]
yes i installed "npm install ng2-restangular --tag dev"... and it will shows the version like 0.1.23

**Comment by davidbonachera** [comment]
I installed the dev version and i still have the error
`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 25:33 in the original .ts file), resolving symbol AppModule in /Users/Enigma/Lab/hubble-web/src/app/app.module.ts
`

Shouldn't be an error from AngularCLI team I think : https://github.com/angular/angular-cli/issues/3707

**Comment by davidbonachera** [comment]
My bad, didn't fully read the updated documentation related to the last 0.1.23 

I updated README also #13
