### ISSUE TITLE
How to directly post without get for example for login

### ISSUE THREAD

**Issue by moorthi07** [2muchcoffeecom/ngx-restangular#60]
How to directly post without get for example for login

Here is my end point user/login that takes input un, pwd and returns user object

let newAccount = { "username": "kkkk", "password":"kkkk"};

// POST /User/Login
this.restangular.all('/users/login').post(newAccount);

**Comment by logvinoleg89** [comment]
Hi @moorthi07, try this
````
this.restangular
.one('users')
.one('login')
.customPOST(newAccount)
````

**Comment by moorthi07** [comment]
Tx, This  works , but further calls to getlist after 'login' as below not fetching result.
```
  ngOnInit() {
      //Treenode - populate data
    this.nodeService.getFiles().then(files => this.files = files);


    // let newUser = this.restangular.all('/users/login'); 
 let newAccount = { "username": "jgjjjhj@yahoo.com", "password":"xxxxx "};
    
    // POST /User
    // newUser.post(newAccount);
    this.me = this.restangular
.one('users')
.one('login')
.customPOST(newAccount).subscribe(user => {
      this.me = user;
        console.log("meOK",this.me.uid);   ---------  This  works
 
 this.heroes = this.restangular.all("posts");


// // loading post resource
     this.heroes.getList().subscribe( hers => {            ------------- no result
      this.heroList = hers;
      console.log('this.heroList ',this.heroList );    
    });

//  this.gsvc.getPosts().then( heroes => {
//       this.heroList = heroes;
//       console.log('this.heroList ',this.heroList );
//     });
    });
// () => {

```
--------------------- part of console output
 `
reqParams
:
Request
contentType
:
0
headers
:
Headers
method
:
0
responseType
:
null
url
:
"http://localhost:2403/posts"
withCredentials
:
false
_body
:
null
__proto__
:
Body
restangularCollection
:
true
restangularized
:
true
route
:
"posts"
`
