### ISSUE TITLE
ngx-restangular imports the whole rxjs 

### ISSUE THREAD

**Issue by ipassynk** [2muchcoffeecom/ngx-restangular#61]
ngx-restangular-http.ts imports the whole rxjs library that is too big. It is recommended to import jut Observable and after that all operators that are used by the application one by one. Like that:

```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/forkJoin';
import 'rxjs/add/observable/throw';
import 'rxjs/add/observable/empty';

import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/concat';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/distinctUntilChanged';
....
```

**Comment by logvinoleg89** [comment]
@ipassynk thanks, this issue is now fixed, version 1.0.6

**Comment by logvinoleg89** [comment]
@ipassynk We have to revert those changes because of community reaction #65

**Comment by ipassynk** [comment]
Angular itself doing everything possible to make the bundle smaller as much as possible and I think all libraries should follow this principal.
