### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tal-shahar** [2muchcoffeecom/ngx-restangular#64]
This is psudo code:
```TypeScript
export class BasicServiceQuery {
  private _offset: number;
  private _limit: number;

  get offset(): number {
    return this._offset;
  }

  set offset(value: number) {
    this._offset = value;
  }

  get limit(): number {
    return this._limit;
  }

  set limit(value: number) {
    this._limit = value;
  }
}

let _serviceQuery: BasicServiceQuery = new BasicServiceQuery;
_serviceQuery.offset = 0;
_serviceQuery.limit = 10;

return this.restangular.all('end_point_name').getList(_serviceQuery);
```

When this code is activated this is the link that is used:
end_point_name?_limit=10&_offset=0&limit=10&offset=0

Why the duplication?
and can it be prevented?

**Comment by logvinoleg89** [comment]
Hi @tal-shahar, this is not a bug, a more detailed description you can find in this [issue](https://github.com/Microsoft/TypeScript/issues/10093).

**Comment by tal-shahar** [comment]
```TypeScript
export class BasicServiceQuery {
  private offset: number;
  private limit: number;

  public get_offset(): number {
    return this.offset;
  }

  public set_offset(value: number) {
    this.offset = value;
  }

  public get_limit(): number {
    return this.limit;
  }

  public set_limit(value: number) { 
    this.limit = value;
  }
}
```
What about functions? shouldn't RestAngular ignore at least them?
Because at the moment it doesn't...
I tried this approach and got this link:
 end_point_name?offset=0&limit=10&get_offset=function%20()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.offset;%0D%0A%20%20%20%20%7D&set_offset=function%20(value)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.offset%20=%20value;%0D%0A%20%20%20%20%7D&get_limit=function%20()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.limit;%0D%0A%20%20%20%20%7D&set_limit=function%20(value)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.limit%20=%20value;%0D%0A%20%20%20%20%7D

**Comment by tal-shahar** [comment]
Hi @logvinoleg89, above.
