### ISSUE TITLE
Error: Uncaught (in promise): TypeError: subject.filter is not a function restangularizeResponse

### ISSUE THREAD

**Issue by reviloera** [2muchcoffeecom/ngx-restangular#65]
Am getting that error when I try to run on Ionic3

`
      let apiPath = this.Restangular.all('/site/createSite');

      let loading = this.loadingCtrl.create({
        content: 'Please wait...'
      });

      loading.present();

      apiPath.post(data).toPromise().then(function (response){

        
        loading.dismiss();

      }, () =>{   // out put error here

       
        loading.dismiss();
      });`

**Comment by logvinoleg89** [comment]
Please share more details :)

**Comment by reviloera** [comment]
Am making a post request to the server, it does the post successfully (I can log the server and see ) however when processing the response am getting that error. I hope am clear , thanks for responding

**Comment by iCodr8** [comment]
I have the same problem with v1.0.8 and Angular 4.0.3

![code](https://cloud.githubusercontent.com/assets/1264033/25483332/9c022c6c-2b55-11e7-9b6a-d6c3f73e78d4.png)
![error](https://cloud.githubusercontent.com/assets/1264033/25483334/9c04411e-2b55-11e7-9655-eda6e7444185.png)
![problem](https://cloud.githubusercontent.com/assets/1264033/25483333/9c03a966-2b55-11e7-839c-53a4bfa484e2.png)

**Comment by iCodr8** [comment]
Problem exists since `1.0.6` because in `1.0.5` it is working.

**Comment by logvinoleg89** [comment]
Hi @reviloera, @iCodr8 please, update to v1.0.9

**Comment by iCodr8** [comment]
Works fine. thx!
