### ISSUE TITLE
How to cancel a request?

### ISSUE THREAD

**Issue by stevebering** [2muchcoffeecom/ngx-restangular#67]
In Restangular 1.x, you can cancel a request by returning a rejected promise to the timeout of the httpConfig option in a FullRequestInterceptor. I would like to be able to do the same thing in ngx-restangular when I do not have an auth token, so I can send the user to the login screen. This doesn't seem to work, however. Do you have any ideas on how I might cancel a request in the FullRequestInterceptor? I don't have a subscription within the context of the interceptor, so I cannot dispose of the subscription at that point. I am looking for ideas.

Thanks and thanks for the great work on this project.

**Comment by logvinoleg89** [comment]
@stevebering, for now we don't have a solution for request cancellation. But errorInterceptor can help to solve this problem. Please follow this  [link](https://github.com/2muchcoffeecom/ngx-restangular#adderrorinterceptor) to find the description on how to update token after authorisation error, as well as how to make redirect to login page.
Thank you for your appreciation of our work.
