### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by tal-shahar** [2muchcoffeecom/ngx-restangular#68]
question

This error is printed out:
npm WARN ngx-restangular@1.0.9 requires a peer of @types/lodash@^4.14.62 but none was installed.

The lodash@4.17.4 is installed? how can this be fixed?

**Comment by rshchpkn** [comment]
Hello @tal-shahar. In project where you are installing ngx-restangular you have version of @types/lodash lower then 4.14.62
