### ISSUE TITLE
Use separate loash modules 

### ISSUE THREAD

**Issue by tamascsaba** [2muchcoffeecom/ngx-restangular#69]
restangular require full of lodash, but only use 25 modules of more than 300.
```
_.isArray
_.includes
_.isUndefined
_.isFunction
_.defaults
_.each
_.extend
_.has
_.initial
_.clone
_.isNull
_.map
_.reduce
_.isBoolean
_.keys
_.reduce
_.forEach
_.isObject
_.bind
_.union
_.values
_.pick
_.every
_.get
_.omit
```

Full lodash: **527 KiB**
Webpack analyse: 
![image](https://cloud.githubusercontent.com/assets/3479963/25989370/1be8d33e-36fc-11e7-87fb-287ba27af80e.png)

**Comment by tamascsaba** [comment]
@logvinoleg89 ???

**Comment by logvinoleg89** [comment]
Hi @tamascsaba, please update ngx-restangular.

**Comment by tamascsaba** [comment]
Restangular import lodash ones, but the full source of lodash. I use 1.0.10:
![image](https://cloud.githubusercontent.com/assets/3479963/26146837/dcabaef4-3af1-11e7-83c1-c91f2e08dfe4.png)

**Comment by logvinoleg89** [comment]
@tamascsaba should be working now.

**Comment by tamascsaba** [comment]
works, thx :+1:
