### ISSUE TITLE
it would be great to check if headers were present in response 

### ISSUE THREAD

**Issue by bartes** [2muchcoffeecom/ngx-restangular#70]
https://github.com/2muchcoffeecom/ngx-restangular/blob/e1679e7af3ca9cac0d3dbc77decfd32b2d4dcc34/src/ngx-restangular.ts#L387

**Comment by logvinoleg89** [comment]
@bartes We can perform the check on headers but can you please specify the situation in which you need it?

**Comment by bartes** [comment]
I found myself uncomfortable with adding empty headers to mockedResponses in specs, 
but if you think that this is not a good enough reason then please close this issue.

**Comment by logvinoleg89** [comment]
@bartes thanks for your answer. We'll consider the necessity of such check with the team if there are more similar issues. Closing this one for now.
