### ISSUE TITLE
Getting the result object inside subscribe().

### ISSUE THREAD

**Issue by Sobiru** [2muchcoffeecom/ngx-restangular#71]
Let's say I have a get request such as below: 

    this.restangular.one('api/user/info').get()
      .subscribe(
        (result) => {
            // Do something with result json object returned by the server.
        });

The problem is, when the server returns the result, in the subscribe function, `result` is another Restangular object instead of the actual result. How could I get the actual result object in the `subscribe()`?

**Comment by logvinoleg89** [comment]
@Sobiru you can use result.plain() that returns the plain element received from the server without any of the enhanced methods. Otherwise you can use setPlainByDefault.
