### ISSUE TITLE
Multiple URL-s

### ISSUE THREAD

**Issue by kotmatpockuh** [2muchcoffeecom/ngx-restangular#72]
For example in angular 1.x i was able to create multiple factories to handle different destinations (for example: files, auth etc).
How can i use multiple `RestangularProvider` in angular 4?

**Comment by logvinoleg89** [comment]
@kotmatpockuh please, check this [link](https://github.com/2muchcoffeecom/ngx-restangular#how-to-create-a-restangular-service-with-a-different-configuration-from-the-global-one)

**Comment by kotmatpockuh** [comment]
@logvinoleg89 U sure it's working with angular 4?
compiler.es5.js:1540 Uncaught Error: Can't resolve all parameters for SomeService: ([object Object], ?).

**Comment by logvinoleg89** [comment]
@kotmatpockuh This is not restangular issue. This error erases when token is being imported. To include token and factory to a separate file should solve the issue.
