### ISSUE TITLE
AoT problem

### ISSUE THREAD

**Issue by bartes** [2muchcoffeecom/ngx-restangular#73]
ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CONFIG_OBJ  in /node_modules/ngx-restangular/dist/esm/src/ngx-restangular.module.d.ts

**Comment by bartes** [comment]
restoring npm back to 4.2 from 4.6 resolved that.

**Comment by logvinoleg89** [comment]
Thank you, it's good you resolved the issue. We'll check the possible reason of this on our side as well.
