### ISSUE TITLE
Mismatch between NPM main and dist main

### ISSUE THREAD

**Issue by LockonF** [2muchcoffeecom/ngx-restangular#74]
As of version 1.0.10 (installed using NPM), the package.json file says that the main file is
` "main": "./dist/umd/ngx-restangular.js"`. When it is still named ng2-restangular.js

It seems that for some reason the NPM package hasn't been updated

**Comment by tairezzzz** [comment]
I couldn't reproduce this issue. I suggest reinstalling ngx-restangular will solve it.
