### ISSUE TITLE
Warning when using forRoot([authService], RestangularConfigFactory)

### ISSUE THREAD

**Issue by Xepe** [2muchcoffeecom/ngx-restangular#75]
Hello, 
I am getting the following warning:

Warning: Can't resolve all parameters for RestangularConfig in ../src/app/restangular.config.ts: (?, ?). This will become an error in Angular v5.x

I was looking for class or interface for RestangularProvider, but I could not find it. 

regards.

**Comment by kotmatpockuh** [comment]
almost the same for me...

**Comment by logvinoleg89** [comment]
@Xepe @kotmatpockuh Can you describe the issue in more details, such as what seed and AOT were used etc. I couldn't reproduce warning using Angular CLI 1.0.0

**Comment by Xepe** [comment]
This happens when instead of using  a export function for:

` RestangularModule.forRoot([Injector], RestangularConfig) `

I use a class with @Injectable like:

```
@Injectable()
export class RestangularConfig {
 constructor(private RestangularProvider: any, private injector: any) { }
}
```

**Comment by logvinoleg89** [comment]
@Xepe the services cannot be used for ngx-restangular configuration. Please, use class for that but not @Injectable decorator.
