### ISSUE TITLE
Subscribe on put()

### ISSUE THREAD

**Issue by Eswan** [2muchcoffeecom/ngx-restangular#77]
When i'm subscribing to a put function : 
`this.customer.put().subscribe((customer) => {
      console.log(customer);
 });`

It is working as expected, but i'm getting a TypeScript error because put() should (for the model) return void.

> TS2339: Property 'subscribe' does not exist on type 'void'.

So, what would be the best way to catch server result from put function ?

Thanks

**Comment by Eswan** [comment]
I solved my problem with a little "trick" : 
`update(customer): Observable < Customer > {
    return customer.put();
  }`

**Comment by logvinoleg89** [comment]
@Eswan can you describe this issue occurred in more details as well as steps to reproduce it.  Angular CLI was used for testing purposes.

**Comment by Eswan** [comment]
My bad, i found the problem.

customer is a Customer object. In order to use restangular functions on it without TS errors, it extends a custom parent class "Restangularize" with "save()", "put()"... attributes. But theses functions don't return "Observable". That was the problem, but solved now =D

I don't know if extends a Restangularize class is the best way to do but i didn't find any better solution.

(sry for my english :) )

**Comment by logvinoleg89** [comment]
@Eswan no problem. Our team is always ready to assist if needed.
