### ISSUE TITLE
Can't resolve 'lodash/omit' with v1.0.11 but no with 1.0.5

### ISSUE THREAD

**Issue by DarkIsDude** [2muchcoffeecom/ngx-restangular#78]
Hi all,

I have a bug.

With ngx-restangular 1.0.11, when I do `ng build --prod` I have the following issue:
```
ERROR in ./~/ngx-restangular/dist/esm/src/lodash.js
Module not found: Error: Can't resolve 'lodash/omit' in '/app/node_modules/ngx-restangular/dist/esm/src'
 @ ./~/ngx-restangular/dist/esm/src/lodash.js 26:11-33
 @ ./~/ngx-restangular/dist/esm/src/ngx-restangular.config.js
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```
Many times but always with lodash (sometime omit, or find or isNumber, ...).

But with 1.0.5, all compile. How can I help you? What do you need?

**Comment by logvinoleg89** [comment]
@DarkIsDude Unfortunately, I couldn't reproduce the issue with ngx-restangular 1.0.11 and Angular CLI 1.0.0. We'll try different versions Angular CLI, it might help to reproduce this issue. 
 It would be also really helpful to get to know more about used environment, such as versions etc.

**Comment by logvinoleg89** [comment]
the issue is being closed per no details provided.
