### ISSUE TITLE
Is ErrorInterceptor Working

### ISSUE THREAD

**Issue by carlosthe19916** [2muchcoffeecom/ngx-restangular#8]
Hello, I was trying to use this library but I had a problem using addErrorInterceptor. Error Interceptor is correctly working? I see the tests and I notices that test of ErrorInterceptor was comented...please let me know if I should use it or will be available soon?

**Comment by rshchpkn** [comment]
AddErrorInterceptor should work properly so if you had problem could you send me more information about  it
