### ISSUE TITLE
AuthService issue for addErrorInterceptor

### ISSUE THREAD

**Issue by xyrintech** [2muchcoffeecom/ngx-restangular#86]
As we are putting the code in app.module.ts and we are passing an object of AuthService, this raises an error for when we make use this.

**Comment by xyrintech** [comment]
Maximum call stack size exceeded

this is the error I am getting on this.

**Comment by logvinoleg89** [comment]
@xyrintech, the similar problem was already resolved in issue #76:
you can't include 2 services to each other as you get the endless cycle. To solve this problem you can use the 3rd service and to extract the necessary functionality to it.
