### ISSUE TITLE
ResponseType: arraybuffer does not work

### ISSUE THREAD

**Issue by Michel73** [2muchcoffeecom/ngx-restangular#87]
I'm getting a JSON.parse error `"Unexpected token P in JSON at position 0"` when I use `this.restangular.one('collection', entry._id).one('action').withHttpConfig({responseType: 'arraybuffer'}).get()`. It seems that response is handled as JSON instead of a stream. In restangular-1 it worked.
Used version: `ngx-restangular: 1.0.11`

**Comment by logvinoleg89** [comment]
@Michel73 currently that is not performed on ngx-restangular.
