### ISSUE TITLE
Handling observables in interceptors

### ISSUE THREAD

**Issue by mrichar1** [2muchcoffeecom/ngx-restangular#88]
I'm currently looking to use some methods in `addResponseInterceptor` function which return observables. 

With the current code for `getList` explicitly raises an error if the resulting data is not an `array`: https://github.com/2muchcoffeecom/ngx-restangular/blob/7ffda9bb32740ef7acbdbc31e088cf4a52958cda/src/ngx-restangular.ts#L423-L425

This means that you can't use observables or promises in interceptors.

Additionally, I can't find a way to resolve the observable 'inside' the interceptor and have the actual data returned from the interceptor (though I am relatively new to observables/promises so might be missing something here).

**Comment by mrichar1** [comment]
See also https://github.com/mgonto/restangular/issues/1153

**Comment by rshchpkn** [comment]
Hello @mrichar1. Unfortunately you can't use observables or promises in response interceptors. It might be implemented in next major version of restangular.
