### ISSUE TITLE
responseType is never set when request with Http Config

### ISSUE THREAD

**Issue by Aaron-Redmond** [2muchcoffeecom/ngx-restangular#89]
I'm currently trying to set the the response type of a request to blob so that restangular does not try to convert the response to json.  
` this.restangular.oneUrl('file/').withHttpConfig({responseType: ResponseContentType.Blob}).get( )
     .subscribe(data => {
       this.downloadFileInternal(data)
     });`
 The responseType is being ignored in the createRequestOptions method of RestangularHelper  
```
 static createRequestOptions(options) {
    let requestQueryParams = RestangularHelper.createRequestQueryParams(options.params);
    let requestHeaders = RestangularHelper.createRequestHeaders(options.headers);
    let methodName = options.method.charAt(0).toUpperCase() + options.method.substr(1).toLowerCase();
    let withCredentials = options.withCredentials || false;
    
    let requestOptions = new RequestOptions({
      method: RequestMethod[methodName],
      headers: requestHeaders,
      search: requestQueryParams,
      url: options.url,
      body: options.data,
      withCredentials,
//RESPONSE TYPE NOT INCLUDED
    });
```
and is therefore always null.
Is there another way to set the respnseType?

**Comment by rshchpkn** [comment]
Hello @Aaron-Redmond, Thank you for pull request. It's merged and new version will be pushed to npm in closest time.
