### ISSUE TITLE
ngx-restangular is not compatible with HttpInterceptor

### ISSUE THREAD

**Issue by jonapoirier** [2muchcoffeecom/ngx-restangular#95]
Angular 4.3 comes up with new HTTP tools, including HttpInterceptor ! 
More docs [here](https://angular.io/guide/http#advanced-usage) 

A simple call to a restangular method like : 
`this._restangular.all('foo').getList();` 
don't trigger the intercept method of HttpInterceptor  :(

Specs from package.json :
`    "dependencies": {
        "@angular/animations": "^4.3.3",
        "@angular/cdk": "^2.0.0-beta.8",
        "@angular/common": "^4.3.3",
        "@angular/compiler": "^4.3.3",
        "@angular/core": "^4.3.3",
        "@angular/forms": "^4.3.3",
        "@angular/http": "^4.3.3",
        "@angular/material": "^2.0.0-beta.8",
        "@angular/platform-browser": "^4.3.3",
        "@angular/platform-browser-dynamic": "^4.3.3",
        "@angular/router": "^4.3.3",
        "angular2-logger": "^0.6.0",
        "angular2-moment": "^1.6.0",
        "bootstrap-sass": "^3.3.7",
        "core-js": "^2.5.0",
        "hammerjs": "^2.0.8",
        "ng2-toastr": "^4.1.2",
        "ngx-restangular": "^1.0.11",
        "ngx-webstorage": "^1.8.0",
        "rxjs": "^5.4.2",
        "zone.js": "^0.8.16"
    },`

**Comment by ashgibson** [comment]
This is probably because ngx-restangular uses the Http library under the hood and not HttpClient which is the library you are referring to.

**Comment by rshchpkn** [comment]
Hello @jonapoirier, @ashgibson is right. Ngx-restangular is using Http class. For intercepting request you should use restangular methods such as [addResponseInterceptor](https://github.com/2muchcoffeecom/ngx-restangular#addresponseinterceptor), [addFullRequestInterceptor](https://github.com/2muchcoffeecom/ngx-restangular#addfullrequestinterceptor), [addErrorInterceptor](https://github.com/2muchcoffeecom/ngx-restangular#adderrorinterceptor)

**Comment by chorsnell** [comment]
@rshchpkn this doesn't actually let me intercept the request though, just modify it?

As in https://github.com/2muchcoffeecom/ngx-restangular/issues/153 I'm trying to mock requests with a fake back end, and it doesn't appear to be possible like you'd be able to with `HttpInterceptor`

Also it looks like HttpClient was merged in https://github.com/2muchcoffeecom/ngx-restangular/pull/133, so should `HttpInterceptor` now work? As it isn't as per 3.0.0.
