### ISSUE TITLE
Should I unsubscribe the observable from restangular in ngOnDestroy method?

### ISSUE THREAD

**Issue by yudream** [2muchcoffeecom/ngx-restangular#99]
Should I unsubscribe the observable from restangular in ngOnDestroy method? Thanks.

**Comment by logvinoleg89** [comment]
Hi @yudream, yes, you have to unsubscribe each time when you don’t need a subscription.

**Comment by kotmatpockuh** [comment]
@logvinoleg89 

Are you sure?

https://stackoverflow.com/questions/35042929/do-you-need-to-unsubscribe-from-angular-2-http-calls-to-prevent-memory-leak

https://stackoverflow.com/questions/38023480/angular-2-subscribe-unsubscribe-observables-in-case-of-http-calls
